Terracotta-OSS/terracotta-core

dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/objectserver/persistence/InMemoryKeyValueStorage.java
dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformPersistentStorage.java
dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformStorageConfiguration.java
dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformStorageProviderConfiguration.java
dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformStorageServiceProvider.java

This PR introduces a new IPersistentStorage impl, NullPlatformPersistentStorage which doesn't persist any data and replaces platform persistence with this if platform is not restartable. We can change the name of this persistor if current one is confusing.

[TAB-6554] Replace platform persistence with null persistor if platform is not restartable

---

common/src/main/java/com/tc/async/impl/OrderedSink.java
dso-l2/src/main/java/com/tc/l2/api/ReplicatedClusterStateManager.java
dso-l2/src/main/java/com/tc/l2/ha/ReplicatedClusterStateManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/api/ServerEntityRequest.java
dso-l2/src/main/java/com/tc/objectserver/entity/AbstractServerEntityRequest.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/NoReplicationBroker.java
dso-l2/src/main/java/com/tc/objectserver/entity/PassiveReplicationBroker.java
dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/ReplicatedEntityRequestImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityRequestImpl.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/test/java/com/tc/classloader/ServiceLocatorTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/RequestProcessorTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ServerEntityRequestImplTest.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationEnvelope.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java
tc-messaging/src/main/java/com/tc/object/EntityID.java

This PR is a rollup of issues #6, #7, and #8.  Three major themes are covered.  
Replicated messages are filtered on the active side and replicated messages are queued during the sync of a key on the passive side and only executed once the sync of a key is complete.
invoke path through ManagedEntity has been refactored to be more specialized for different message types received.
State transition from PASSIVE_STANDBY to ACTIVE has been further refined to handle multiple passives.  When a PASSIVE transitions to ACTIVE, the new active must discover other servers that lost election but are in PASSIVE_STANDBY mode.  These servers can continue to receive replicated messages from the new active as they are in the same state as the new ACTIVE.
Also included are some minor bug fixes for message …

Active passive cleanup

---

dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
dso-l2/src/main/java/com/tc/objectserver/api/ServerEntityRequest.java
dso-l2/src/main/java/com/tc/objectserver/entity/AbstractServerEntityRequest.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/main/java/com/tc/objectserver/entity/ClientEntityStateManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ReplicatedEntityRequestImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityRequestImpl.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/test/java/com/tc/objectserver/entity/RequestProcessorTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ServerEntityRequestImplTest.java
tc-messaging/src/main/java/com/tc/entity/NetworkVoltronEntityMessageImpl.java
tc-messaging/src/main/java/com/tc/entity/ResendVoltronEntityMessage.java
tc-messaging/src/main/java/com/tc/entity/VoltronEntityMessage.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java

ManagedEntityImpl$PassiveSyncServerEntityRequest holds the target passive in the wrong place.  This resulted in resets getting sent to every passive every time a new passive connects.  This did not work in 2 passive scenarios.  ServerEntityRequest still needs to be refactored a bit to make clear that a request result should be sent to a passive or a client but that should be a different branch.

Two passive sync fix

---

dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java

ClientEntityManagerTest is racy because it tries to reuse the same test batches.  Rework mocking so a new batch is created on each request.

fix racy test with different mocking

---

dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
dso-l2/src/main/java/com/tc/objectserver/handler/ChannelLifeCycleHandler.java

-this avoids the problem where the events would also be called for the replicated information, on the passive
-we can also now re-enable the assertions to verify event call symmetry in ManagementTopologyEventCollector

Issue 28: Moved ITopologyEventCollector client callsites to channel methods

---

connection-impl/src/main/java/com/terracotta/connection/entity/MaintenanceModeService.java

force maintenance mode locking to use the user thread rather than an executor service.  The executor service is non-daemon and prevents system exit once user threads are finished.

Fix #63 - Use the incoming thread to execute locking

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java

-we now wrap every call to the serailizer from within the platform in a try-catch
-if a MessageCodecException is thrown, it is wrapped in EntityUserException and re-thrown
-if any other runtime exception is thrown, it is wrapped in a MessageCodecException, then a EntityUserException and re-thrown

Implement support for MessageCodecException

---

dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/services/BuiltInServiceProvider.java
dso-l2/src/main/java/com/tc/services/CommunicatorService.java
dso-l2/src/main/java/com/tc/services/DelegatingServiceRegistry.java
dso-l2/src/main/java/com/tc/services/EntityClientCommunicatorService.java
dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistry.java
dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistryImpl.java

For now, this largely just creates a parallel registration and look-up path but creates the groundwork for allowing these to split in more meaningful ways, over time

Built-in registration is now distinct from external implementation registration

---

common/src/main/java/com/tc/properties/TCPropertiesConsts.java
common/src/main/resources/com/tc/properties/tc.properties
dso-l2/pom.xml
dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/NoopEntityMessage.java
dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
tc-messaging/src/main/java/com/tc/entity/VoltronEntityMessage.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java

This PR makes MGMT_KEY more exclusive than before.  MGMT_KEY currently flushes all the request queues but does not prevent subsequently submitted requests from overrunning the event on the MGMT_KEY.  The provides a deferment queue so that new messages on this queue are not submitted request processor until after the MGMT_KEY event completes.
Also included in this PR is a bug fix in the passive execution pipeline.

MGMT key deferred execution

---

dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
dso-l2/src/main/java/com/tc/services/BuiltInServiceProvider.java
dso-l2/src/main/java/com/tc/services/CommunicatorService.java
dso-l2/src/main/java/com/tc/services/DelegatingServiceRegistry.java
dso-l2/src/main/java/com/tc/services/EntityClientCommunicatorService.java
dso-l2/src/main/java/com/tc/services/InternalServiceRegistry.java
dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistry.java
dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
dso-l2/src/test/java/com/tc/services/CommunicatorServiceTest.java

-also updated the corresponding test to use this type and provide a mock codec for serialization

Fix #78: Updated EntityClientCommunicatorService to use EntityResponse as its argument type

---

dso-l2/src/main/java/com/tc/objectserver/handler/ChannelLifeCycleHandler.java
dso-l2/src/test/java/com/tc/objectserver/handler/ChannelLifeCycleHandlerTest.java

-we check to see if a disconnected event corresponds to a channel with no local address since those are synthetic events and we don't want to pass those to ITopologyEventCollector

Fix #82: Filter out synthetic disconnected events

---

terracotta-kit/src/assemble/distribution.xml

For some use cases (windows, automated tests) the zip format is friendlier than a tarball

Add zip format to kit

---

dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/handler/EntityExistenceHelpers.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/persistence/EntityData.java
dso-l2/src/main/java/com/tc/objectserver/persistence/EntityPersistor.java
dso-l2/src/test/java/com/tc/objectserver/persistence/EntityPersistorTest.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java

The general contract the platform provides for its entities is that the same message may be seen more than once, but always in the same order, relative to the messages around it.  They are expected to be able to handle these re-sent message, however.
The platform wasn't honouring that, internally, for its own message types.  This meant that a re-sent create, for example, would fail on re-send, giving the client an inconsistent response.
This change resolves that by recording the recent entity life-cycle messages in an event journal, in the EntityPersistor, so that they can be short-circuited to reply with the same response they originally gave, if they exist in the journal.

Handle re-sent create/destroy/doesExist/reconfigure messages

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java

This PR brings changes to crash the server if entity MessageCodec.deserialize(...)/deserializeForSync(...) returns null.

Fix #91: crash the server if entity deserializer returns null

---

dso-l2/src/main/java/com/tc/objectserver/entity/AbstractServerEntityRequest.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/test/java/com/tc/objectserver/entity/ActiveToPassiveReplicationTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java

Fix issue #102. 
* Use futures to control flow after scheduling a request
* Control sync flow from the active rather than the passive by only sending the next message after completion of the previous sync message

Fix sync execution

---

common/src/main/java/com/tc/async/impl/OrderedSink.java
dso-l1/src/main/java/com/tc/object/ClientBuilder.java
dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
dso-l1/src/main/java/com/tc/object/DistributedObjectClientFactory.java
dso-l1/src/main/java/com/tc/object/StandardClientBuilder.java
dso-l1/src/main/java/com/tc/object/request/RequestReceiveHandler.java
dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/main/java/com/tc/objectserver/handler/ChannelLifeCycleHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/test/java/com/tc/objectserver/handler/ChannelLifeCycleHandlerTest.java

Logging changes
Flush the voltron response sink before sending resends.  If the response Sink is not flushed, a double remove can result.
Channel events should only be observed by the topology collector on the active.

Bug fixes 2

---

terracotta-kit/src/assemble/server/bin/start-tc-server.sh

Let me know what you think about this.
The approach of using SIGTERM when we handle the SIGINT is probably safe enough but I do wonder if there is a better way to handle the loop on wait.

Loop on wait call and send SIGTERM on SIGINT

---

dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFilePersistentStorage.java
dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageServiceProvider.java
dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformStorageServiceProvider.java
dso-l2/src/main/java/com/tc/objectserver/persistence/Persistor.java
dso-l2/src/main/java/com/tc/objectserver/persistence/TestClusterStatePersistor.java
dso-l2/src/main/java/com/tc/services/BuiltInServiceProvider.java
dso-l2/src/main/java/com/tc/services/CommunicatorService.java
dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistry.java
dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistryImpl.java
dso-l2/src/test/java/com/tc/server/TestServiceProvider.java

Implement clear() method for all ServiceProvider and IPersistentStorage implementations
Clear all Services state if dirty db is set

Fix #5 - Follow up changes for Service API change

---

common/src/main/java/com/tc/net/core/SocketParams.java
common/src/main/java/com/tc/properties/TCPropertiesConsts.java
common/src/test/java/com/tc/net/core/NoReconnectThreadTest.java
common/src/test/java/com/tc/net/core/OOOReconnectTimeoutTest.java
common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java
common/src/test/java/com/tc/net/protocol/transport/HealthCheckerMonitorThreadEngineTest.java
common/src/test/java/com/tc/util/TCPropertiesConstsTest.java
dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
dso-l2/src/main/java/com/tc/l2/logging/TCLoggingLog4J.java
dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
dso-l2/src/main/java/com/tc/net/utils/L2Utils.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/test/java/com/tc/config/TcPropertiesWithSpacesOverWriteTest.java
dso-l2/src/test/java/com/tc/net/groups/TCGroupManagerImplTest.java

* replace tc properites string literals usage with named constants
* remove unnecessary public static final usage in TCPropertiesConsts interface
* create subcategories for use with TCProperties.getPropertiesFor(...)

Fix #137 - cleanup tc properties

---

dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
dso-l2/src/test/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManagerTest.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationEnvelope.java

Fix the reconnect timeout assertion by executing resends from the proper stage.
Fix destroy during sync hang and create during sync miss with new unit test and refactoring of ReplicationSender and ReplicatedTransactionHandler
Close hooks for release of entities do not operate as documented.  fix by making sure the close hook is not called on exception.

Clean client entity mgr

---

connection-impl/src/main/java/com/terracotta/connection/entity/MaintenanceModeService.java

-these were remnants of a previous design approach which seemed to be over-designed in light of the very simple, in-order, approach we now have
-removing these components make the simplicity of the current design more obvious

Removed DirectExecutor, TryLockRunnable, and the Future interactions

---

common/src/main/java/com/tc/net/protocol/tcm/ClientMessageChannelImpl.java
common/src/main/java/com/tc/object/msg/TestClientHandshakeMessage.java
dso-l2/src/main/java/com/tc/objectserver/core/api/ITopologyEventCollector.java
dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java
tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeMessage.java
tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeMessageImpl.java

1. Follow API changes in Terracotta-OSS/terracotta-apis#47
2. Add Client PID to ClientHandshakeMessage and send it during handshake 
3. API change for ITopologyEventCollector.clientDidFetchEntity to include ClientDescriptor 
4. Add corresponding unit tests

Expose Client PID info on Server side

---

dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/services/EntityMessengerProvider.java
dso-l2/src/main/java/com/tc/services/EntityMessengerService.java
dso-l2/src/test/java/com/tc/services/EntityMessengerProviderTest.java

-provided via the built-in provider: EntityMessengerProvider
-DistributedObjectServer initializes this with the same message sink used by incoming network entity messages
-note that the "fake" messages enqueued by this service can be identified via their null source node.  ProcessTransactionHandler uses this to ensure that it doesn't persist the order of these messages (since they can't be re-sent as they originate internally)
-also added a simple unit test starting-point

Fix #42: Created IEntityMessenger implementation and basic support

---

dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/services/EntityMessengerService.java

-using nulls, directly, causes issues for serialization/deserialization
-these NULL_ID singletons can still be used for logical decisions around how to apply the synthetic messages
-also added the check to ReplicatedTransactionHandler to not persist the synthetic messages

Fix #168: Use NULL_ID singletons instead of null for synthetic message fields

---

dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l1/src/main/java/com/tc/object/EntityClientEndpointImpl.java

-EndpointDelegate.handleMessage() now takes EntityResponse instead of byte[]
**Note:**  This depends on Terracotta-OSS/terracotta-apis#78

Update to account for EndpointDelegate API change

---

dso-l2/src/main/java/com/tc/objectserver/entity/ActivePassiveAckWaiter.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/main/java/com/tc/objectserver/entity/NoReplicationBroker.java
dso-l2/src/main/java/com/tc/objectserver/entity/PassiveReplicationBroker.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/test/java/com/tc/objectserver/entity/ActivePassiveAckWaiterTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ActiveToPassiveReplicationTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/RequestProcessorTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessageAck.java

* this uses a new RECEIVED ack added in the active-passive dialect (note that this is NOT exposed to the client)
* the OLD logic on the active was:  block until passive completes, now run invoke, then return
* the new logic on the active is:  block until passive receives, now run invoke, then block until passive completes, then return
* there are some concerns that exclusive mode might have been relying on some nature of the old ACK ordering but we believe that has changed and none of the tests had a problem
* by injecting a 20ms sleep between the "block for receives" and "invoke", I was able to observe MessageFloodTest running in both orders over the course of a run

Active-passive parallel invoke support

---

dso-l2/src/main/java/com/tc/objectserver/entity/ActivePassiveAckWaiter.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/test/java/com/tc/objectserver/entity/ActivePassiveAckWaiterTest.java

* Fix a leak where we never removed these waiters
* Don't assert that the waiter was waiting for the completed node in the case where the node unexpectedly disappeared

Fix to ActivePassiveAckWaiters handling

---

dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/services/EntityMessengerProvider.java
dso-l2/src/main/java/com/tc/services/EntityMessengerService.java
dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
dso-l2/src/test/java/com/tc/services/EntityMessengerProviderTest.java

The work is split up since much of the change is plumbing.

RetirementManager is now per-entity instance, instead of global

---

dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java

-this kind of exception is state-safe, meaning that we can assume the problem would be mirrored on the passive, meaning that we can return it to the client, wrapped in EntityUserException
-this means that we no longer bring down the server when this exception is thrown

Correctly handle MessageCodecException in ManagedEntityImpl

---

dso-l2/src/main/java/com/tc/objectserver/handler/EntityExistenceHelpers.java
dso-l2/src/test/java/com/tc/objectserver/handler/EntityExistenceHelpersTest.java

When the client id is null, skip the transaction caching.  The action will never be resent.

Fix #208: skip transaction caching for permanent entities

---

dso-l1/src/main/java/com/tc/object/EntityClientEndpointImpl.java

-updated to latest API spec
NOTE:  Depends on Terracotta-OSS/terracotta-apis#112

InvocationBuilder.get() blocks on RETIRED, by default

---

terracotta-kit/src/assemble/server/bin/start-tc-server.sh

start-tc-server.sh uses bash syntax (eg function) but uses sh as the interpreter.   /bin/sh != /bin/bash on many unix flavors (eg Ubuntu, where /bin/sh = dash).   
In other words, this script cannot work without bash, hence it should say so.

Using bash instead of sh

---

terracotta-kit/src/assemble/server/bin/start-tc-server.sh

-this is causing test hangs due to some subtlety of how invoking the bash-emulating sh as "bash" causes it to change some nuance of traps or kill

Reverting this change while we investigate the problem

---

dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityFactory.java

instead of IllegalArgumentException when an entity is not on a class path and create is attempted on the server.

Fix #223 - Throw EntityNotProvided 

---

connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java

-this is a stop-gap to emulate a different locking scheme on top of the existing remnants of maintenance mode
-while it won't give the correct answer in all cases (for example, if the client holding a lock is trying to delete a non-existent entity), it will provide the correct response, and alleviate the locking behavior we no longer want, in the paths EhCache calls (where the lock is only held because the entity exists (a fetch), the entity is about to exist (create), or does exist and is about not to (destroy))
NOTE:  This should probably be rebased and merged _after_ the current set of in-flight PRs.

Fix #212: create() assumes tryLock failure implies entity exists

---

build-parent/pom.xml
client-logging/pom.xml
client-runtime/pom.xml
common/pom.xml
pom.xml
tc-messaging/pom.xml
terracotta-kit/pom.xml

-inline version references replaced with properties
-tc-messaging no longer uses its own version
Someone with Maven knowledge:  does this change make sense and seem right?
It was basically some changes I also needed to make along-side the version release.

Preparing poms for release

---

pom.xml

-terracotta-parent: 5.0.0
-terracotta-apis: 1.0.0.beta
-terracotta-configuration: 10.0.0.beta

Fix #242:  Updated dependencies on terracotta-parent, terracotta-apis, and terracotta-configuration

---

dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java

Partially synced servers cannot participate in elections.  If the server being synced from disappears, force the syncing server to zap itself.

address election corner case

---

connection-impl/src/main/java/com/terracotta/connection/TerracottaConnection.java
connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java
connection-impl/src/test/java/com/terracotta/connection/entity/TerracottaEntityRefTest.java
connection-loader/src/main/java/com/terracotta/connection/ClientHandle.java
connection-loader/src/main/java/com/terracotta/connection/ClientHandleImpl.java
connection-loader/src/main/java/com/terracotta/connection/TerracottaInternalClient.java
connection-loader/src/main/java/com/terracotta/connection/TerracottaInternalClientImpl.java
connection-loader/src/main/java/com/terracotta/connection/api/TerracottaConnectionService.java
dso-l1/src/main/java/com/tc/object/ClientEntityManager.java
dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
dso-l1/src/main/java/com/tc/object/StandardClientBuilder.java
dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/persistence/EntityPersistor.java

remove lock manager from the client.  The server counterpart is already gone
make anything but invokes wait for full retire before sending more messages.  This is to address some lifecycle resend bugs and create entity messages in the context of sync.

Lifecycle cleanup

---

dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
dso-l2/src/main/java/com/tc/objectserver/handler/EntityExistenceHelpers.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java

Fixes issues related to multiple lifecycle operations invoked from multiple clients.
* handle isDestroyed flag in ```ManagedEntity.destroyEntity```
* only remove ManagedEntity from entityManager after the very last NOOP is issued
* properly handle entity not found in ReplicatedTransactionHandler

Fix #280 - Rapid lifecycle from multiple clients

---

dso-l2/src/main/java/com/tc/objectserver/core/api/ITopologyEventCollector.java
dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
pom.xml

-updated dependencies for terracotta-apis 1.0.6.beta and terracotta-configuration 10.0.6.beta
-this is mostly just plumbing the consumerID down through ManagementTopologyEventCollector

Populate consumerID in PlatformEntity

---

dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/objectserver/persistence/EntityData.java
dso-l2/src/main/java/com/tc/objectserver/persistence/EntityPersistor.java
dso-l2/src/test/java/com/tc/objectserver/entity/ActiveToPassiveReplicationTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
tc-messaging/src/main/java/com/tc/l2/msg/PassiveSyncMessage.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java

*  Fix an issue with promotion of a destroyed entity
*  Ship the entity lifecycle log as the last part of passive sync
*  Clean the lifecycle log after each state transition
*  Fix NOOP use in replication
*  Fix ordering on the passive of filtered transactions

Ship lifecycle log

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java

This test did not emulate platform threads properly.  Test threads would fail silently with assertion checks causing tests to fail in strange ways.  Even though these tests still use multiple threads.  Execution is much more linear with flushes of the execution and transaction handler threads being flushed at every point a completion is waited for.  This should clear up any racy behavior.

fix buggy/racy unit test for managed entities

---

dso-l2/src/test/java/com/tc/net/groups/TCGroupManagerNodeJoinedTest.java

TCGroupManagerNodeJoinedTest may have stuck threads that need interrupting

interrupt stuck threads

---

dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/objectserver/impl/ServerBuilder.java
dso-l2/src/main/java/com/tc/objectserver/impl/StandardServerBuilder.java
dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageProviderConfiguration.java
dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageServiceProvider.java
dso-l2/src/main/java/com/tc/server/TCServerImpl.java
dso-l2/src/test/java/com/tc/objectserver/persistence/FlatFileStorageServiceProviderTest.java

This mostly just moves the capability into the location we can use later on in the config change so that the core server doesn't need to worry about file locking or storage locations.  That will become purely a service concern.

FlatFileStorageServiceProvider now handles start-up locking

---

dso-l2/src/main/java/com/tc/objectserver/core/api/ITopologyEventCollector.java
dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java

-this change also bases more of its correctness validations on the underlying service interface (although we may re-add these checks, at this level, in the future)
NOTE:  Will self-merge this since the rest of the team is out.

Fix #337: Change fetch identifier to account for repeated fetches from a client

---

common/src/main/resources/com/tc/config/schema/setup/default-config.xml
dso-l2/src/main/java/com/tc/config/schema/CommonL2Config.java
dso-l2/src/main/java/com/tc/config/schema/CommonL2ConfigObject.java
dso-l2/src/main/java/com/tc/config/schema/setup/L2ConfigurationSetupManagerImpl.java
dso-l2/src/main/java/com/tc/object/config/schema/L2Config.java
dso-l2/src/main/java/com/tc/object/config/schema/L2ConfigObject.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/test/java/com/tc/config/schema/setup/BaseConfigurationSetupManagerTest.java
pom.xml

-we now assume that an implementation has been passed in, via the standard service configuration
-if we do NOT see an implementation of IPersistentStorage, we assume that we are NOT running in a restartable mode and will register an in-memory-only implementation of IPersistentStorage, as before
-also removed the data tag from the default config along with any other config-related objects depending on data, data-backup, or restartable existing in the config
Will self-merge, as discussed.

Fix #342: Update deps and no longer explicitly create the IPersistentStorage

---

dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityRequestImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityRequestResponse.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformPersistentStorage.java
dso-l2/src/main/java/com/tc/objectserver/persistence/TransactionOrderPersistor.java
dso-l2/src/test/java/com/tc/objectserver/entity/ServerEntityRequestImplTest.java
tc-messaging/src/main/java/com/tc/entity/VoltronEntityMultiResponseImpl.java

When there is no persistence, the transaction order sequence still needs to be stored.
Fix a retirement bug.  Late bind channel lookup.

Perf changes.  Optimize the sequence storing

---

dso-l2/src/main/java/com/tc/objectserver/entity/MessagePayload.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
tc-messaging/src/main/java/com/tc/l2/msg/PassiveSyncMessage.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java

This adds the ability to print entity message level information in the debug strings for ReplicationMessages.

Adding ability to add EntityMessage level toString to ReplicatedMessage debugging

---

dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java

-this failed send is possible if the client has disconnected
-while unusual, it isn't wrong

Fix #360: Log, don't assert, on failure to send response

---

dso-l2/src/main/java/com/tc/l2/handler/PlatformInfoRequestHandler.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/services/BestEffortsMonitoring.java
dso-l2/src/main/java/com/tc/services/LocalMonitoringProducer.java
dso-l2/src/test/java/com/tc/services/BestEffortsMonitoringTest.java
dso-l2/src/test/java/com/tc/services/SingleThreadedTimerTest.java
dso-l2/src/test/java/com/tc/services/TestTimeSource.java
tc-messaging/src/main/java/com/tc/l2/msg/PlatformInfoRequest.java

The final version of this uses the SingleThreadedTimer to grab any cached data and sent it to the active.
The unit tests try to demonstrate how it handles the interesting cases where state changes while the timer is pending.

Several steps in handling the pushBestEfforts, along with a unit test

---

dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActivePassiveAckWaiter.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/NoReplicationBroker.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/test/java/com/tc/objectserver/entity/ActivePassiveAckWaiterTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ActiveToPassiveReplicationTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
pom.xml
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessageAck.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationResultCode.java

Handles ConfigurationException coming from the entity implementation.   If an entity throws a ConfigurationException in a lifecycle operation and all nodes of a stripe agree, EntityConfigurationException is returned to the client.  If some succeed and some fail, the failing nodes are zapped and success is communicated back to the client.
Also in this PR is a small fix to logging
A Fix to handling of partially sync'd restartable nodes

Implement passive results

---

dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/api/EntityManager.java
dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/ClientEntityStateManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/handler/EntityExistenceHelpers.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
tc-messaging/src/main/java/com/tc/l2/msg/PassiveSyncMessage.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java

Passive entities must be reference counted the same as actives so they are not deleted prematurely.

Fix destroy

---

dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
dso-l2/src/test/java/com/tc/objectserver/entity/ActiveToPassiveReplicationTest.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationEnvelope.java

These changes most relate to the recently-added asserts in SyncState but also other concerns we had regarding handling of concurrent deletes during sync and some misleading names around the ReplicationEnvelope.

Small fixes

---

common/src/main/java/com/tc/exception/EntityBusyException.java
connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java
connection-impl/src/test/java/com/terracotta/connection/entity/TerracottaEntityRefTest.java
dso-l1/src/main/java/com/tc/object/ClientEntityManager.java
dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l1/src/main/java/com/tc/object/ExceptionUtils.java
dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
dso-l2/src/main/java/com/tc/objectserver/api/ServerEntityRequest.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntitySyncInterop.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntitySyncInteropTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java
tc-messaging/src/main/java/com/tc/l2/msg/SyncReplicationActivity.java
tc-messaging/src/main/java/com/tc/object/EntityDescriptor.java

Lifecycle and sync interaction is improved by not blocking the process transaction handler
Small improvement to not wait for message completion on passives with execution was designated to be only active.
debug message logging
fix an improper assertion about start the start of a replicated message stream.

Improve lifecycle and sync interaction

---

common/src/main/java/com/tc/net/core/TCWorkerCommManager.java
common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java

-simplified the selection of the lightst comm thread which seems to make it less likely to race with other threads
-added more instrumentation to the failing unit test.  The test is probably still failing but has been augmented just to verify if that is the case to justify future simplifications to fix it (validating the total connections, not the weight per thread - even with this fix, that should still be racy)
-an open question if/when we change this test is if the other cases where per-thread weights are validated should also be changed to only validate totals

Re #414: Changed selection of lightest comm thread

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/MessagePayload.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationReplicateMessageIntent.java

This fixes the case when one of multiple passives takes over and the remaining passives join as passive standby.  Rather than not send any messages when sync has never happened, messages always need to be sent to passives when sync has not been started or has finished.  During sync the filter is utilized.  It is up to the receiving passive to decide how to handle incoming messages before sync.  If PASSIVE_UNINITIALIZED, the passive does nothing other than ack the message.  The passive has requested sync and it should be coming soon.  If PASSIVE_STANDBY, the passive will apply the messages as both the newly promoted active and remaining passive standby's are resuming from the same place.

Fix replication on multiple passives when one of the passives takes over

---

common/src/main/java/com/tc/net/core/CoreNIOServices.java
common/src/main/java/com/tc/net/core/TCWorkerCommManager.java

This is an attempt to solve the intermittent failures in TCWorkerCommManagerTest.  The following seems to imply that the test is bogus as it is asserting on code that knows it is racy and is promising only best efforts.
https://github.com/Terracotta-OSS/terracotta-core/blob/master/common/src/main/java/com/tc/net/core/TCWorkerCommManager.java#L74-L79
This is an attempt to make thread selection and weighting more deterministic by saying that each CoreNIOServices worker can be in the process of selection by only one connection at a time.
Quite frankly, I am not totally confident in this change.  Please review and provide feedback.

Try and do better weighting to prevent trivial races

---

common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java
dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java

This can happen when the handshake thread gets descheduled in exactly the right place.  Ordering the calls in the top collector is the best way to handle this.

Fix #427 - capture any fetches prior to getting the connected call.  

---

common/src/main/java/com/tc/net/core/TCConnectionImpl.java
dso-l2/src/main/java/com/tc/objectserver/handler/GroupMessageBatchContext.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java

This changes some of the implementation around message batching.
Most of the work is around the higher-level batching to enable a "force-feeding" of the network, change the maximum batching size, and whether or not we will do any batching, at all.
The high-level catching can now be disabled with tc.property active-passive.inflight=0 (active-passive.inflight=1 is the default we had before this PR, active-passive.inflight=2 is the default now).
Some small lower-level changes were also made, to remove some duplicated calls and disable an optimization which probably wasn't helping (in any case, there would be a better way to make this optimization, if needed, which is a simple adaptation from what I created).

Batching work

---

dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java

-we want to promote and restart entities in the same order they were originally instantiated
-note that the passive sync case will be handled in a later commit
Ideally, this would merge after the other PR regarding diagnostic port support.

Re #439: Sort entities by consumerID before promotion or restart

---

dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java

Make sure entities are not altered by lifecycle during sync.  This is done by doing the following at the beginning sync of an entity under snapshot lock.  
Block the process transaction handler from scheduling new operations on an entity.  Then making sure any operations in the deferment queue are scheduled.  Then only creating supplying creation data only if the entity is valid and not destroyed.

Fix #454 - Entity Sync

---

dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java

These asserts rely on code outside the core.  Switch to warnings and investigate further root cause.

Switch asserts to warnings until further investigation

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
pom.xml

-this also re-orders the monitoring events since we recently loosened the expectations that these followed any specific order, relative to entity API calls

Update to account for new createNew() exception

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
tc-messaging/src/main/java/com/tc/l2/msg/SyncReplicationActivity.java

After conversation it was discovered by @jd0-sag that creating replicated messages was unreasonably expensive.  See #465.  By generating load internally on the server, two hotspots were identified.  The first was the switch case statement in RequestProcessor. createReplicationActivity as a possible culprit.  Changed to an enum map and profiling data suggests that it has helped.  The debug statement optimization is probably trivial.

Perf testing and discussion

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntitySyncInterop.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntitySyncInteropTest.java

This was blocking the release build.  I will self-merge this but assign to @myronkscott in case he has any insight, when he returns (to make sure I did this in a way which makes sense to him).

Fix intermittent hang in ManagedEntitySyncInteropTest

---

terracotta-kit/src/assemble/server/bin/start-tc-server.bat

This PR includes 2 bug fixes for issue https://github.com/Terracotta-OSS/terracotta-core/issues/485
1. 
When the start-tc-server.bat script builds the classpath, sometimes the length of the classpath exceeds 8191 characters which is the max allowed characters for a windows command.  This occurs when the directory path to the script file is very deep.  In my case it was 184 characters deep in the path.
2. 
now allows white space directory names within the classpath.

start-tc-server.bat command exceeds windows max command length

---

connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java
dso-l1/src/main/java/com/tc/object/ExceptionUtils.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
pom.xml
tc-messaging/src/main/java/com/tc/exception/VoltronWrapperException.java

-this allows us to plumb these through the server, and over the wire, without creating a parallel path through the code for the different type of exception
-the client-side decoding just needs to be aware of this

Wrap RuntimeEntityExceptions in VoltronWrapperException

---

common/src/main/java/com/tc/async/impl/StageImpl.java
common/src/main/java/com/tc/async/impl/StageQueueImpl.java
common/src/test/java/com/tc/async/impl/StageQueueImplTest.java

Cleaned up shortest queue algorithm.  Probably still a better way but this at least improves the situation.

Fix #489 - use a more deterministic start and pointer

---

dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l1/src/main/java/com/tc/object/ExceptionUtils.java
dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
pom.xml

-this replaces the previous failure scenarios which threw undefined runtime exceptions, making them all throw ConnectionClosedExceptions
NOTE: The pom.xml must be updated with API release before merging this.

(DO NOT MERGE) Update to use ConnectionClosedException

---

dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/objectserver/persistence/ClientStatePersistor.java
dso-l2/src/main/java/com/tc/objectserver/persistence/EntityPersistor.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
dso-l2/src/test/java/com/tc/objectserver/persistence/EntityPersistorTest.java

On passives, since client source information was not propagated, lifecycle operations are not journaled.  As a result, resent lifecycle operations can give the wrong answer.
TODO: add testing.

Lifecycle journaling broken 

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java

After promotion, an attempted delete should not crash the server.

Fix #519 - Permanent entities should not crash the server

---

dso-l2/src/main/java/com/tc/objectserver/handler/RetirementManager.java
dso-l2/src/main/java/com/tc/services/EntityMessengerService.java
dso-l2/src/test/java/com/tc/services/EntityMessengerServiceTest.java
pom.xml

Adds support for explicit deferment. By decomposing the prior
"message & defer" call into "defer now, message later", we keep the
same well undesrtood implementation with the difference being,
the second message is not sent until the retirement handle is released,
via the release() method.
Note that this means that explicitly deferred messages *must* be
eventually released, or messages will simply hang around.

Issue 510: Add explit retirement deferment

---

dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java

This PR just disables TCMemoryManager monitoring but doesn't remove the code.

Fix #538 - disable TCMemoryManager monitoring

---

connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java
dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l1/src/main/java/com/tc/object/EntityClientEndpointImpl.java
dso-l1/src/main/java/com/tc/object/ExceptionUtils.java
dso-l1/src/main/java/com/tc/object/InFlightMessage.java
dso-l1/src/test/java/com/tc/object/InFlightMessageTest.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/objectserver/impl/PluggableSecurityManager.java
dso-l2/src/main/java/com/tc/objectserver/impl/StandardServerBuilder.java
dso-l2/src/main/java/com/tc/services/BestEffortsMonitoring.java
dso-l2/src/main/java/com/tc/services/LocalMonitoringProducer.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
dso-l2/src/test/java/com/tc/services/BestEffortsMonitoringTest.java
pom.xml
tc-messaging/src/main/java/com/tc/entity/VoltronEntityAppliedResponseImpl.java
tc-messaging/src/main/java/com/tc/exception/VoltronEntityUserExceptionWrapper.java

*  EntityUserException(s) thrown by ActiveServerEntity.invoke() will be logged and sent to the client and PassiveServerEntity.invoke() will be just logged. 
* EntityUserException(s) don't crash the server but other exceptions crash and they will be not sent to the client.

Fix #509: propagate EntityUserException to client

---

common/src/main/java/com/tc/async/impl/AbstractStageQueueImpl.java
common/src/main/java/com/tc/async/impl/MultiStageQueueImpl.java
common/src/main/java/com/tc/async/impl/SingletonStageQueueImpl.java
common/src/main/java/com/tc/async/impl/StageImpl.java
common/src/main/java/com/tc/async/impl/StageQueue.java
common/src/main/java/com/tc/util/UpdatableFixedHeap.java
common/src/test/java/com/tc/async/impl/MultiStageQueueImplTest.java
common/src/test/java/com/tc/async/impl/SingletonStageQueueImplTest.java
common/src/test/java/com/tc/async/impl/StageImplTest.java
common/src/test/java/com/tc/net/protocol/transport/ConnectionHealthCheckReverseCallbackTest.java
common/src/test/java/com/tc/util/UpdatableFixedHeapTest.java

Updated for rework...
For StageQueueImpl, an interface StageQueue was extracted; a factory
is now used to create StageQueue's. This allowed me to split
StageQueueImpl into 2 different implementations. SingletonStageQueueImpl
is used when only 1 queue is desired (allowing for much more efficiency)
in this case, while MultiStageQueueImpl is used for queue counts >1.
In MultiStageQueueImpl, I created an enum for two different shortest path
impls. BRUTE is the classic brute force approach, while PARTITION
simply partitions the queues into sets of 4 (or 2 if the number of
queue is <8, or 1 if <2), and then on each findShortestQueue(),
we choose the next partition, and brute force the shortest queue
within that partition. Since the partitions are so small, the short
brute force search is fast, …

Issue #350 Add more efficient shortest queue selection methods.

---

common/src/main/java/com/tc/config/Directories.java
terracotta-kit/src/assemble/server/bin/start-tc-server.bat
terracotta-kit/src/assemble/server/bin/start-tc-server.sh

Move it to the server folder instead of the kit root. This allows
moving out server from a kit and use that as the set of files to copy
on different hosts.

Fix #578 Update reference directory for server

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/persistence/ClientStatePersistor.java
dso-l2/src/main/java/com/tc/objectserver/persistence/ClusterStatePersistor.java
dso-l2/src/main/java/com/tc/objectserver/persistence/EntityPersistor.java
dso-l2/src/main/java/com/tc/objectserver/persistence/Persistor.java
dso-l2/src/main/java/com/tc/objectserver/persistence/TransactionOrderPersistor.java
dso-l2/src/main/java/com/tc/services/CommunicatorService.java
dso-l2/src/main/java/com/tc/services/EntityMessengerProvider.java
dso-l2/src/main/java/com/tc/services/ImplementationProvidedServiceProvider.java
dso-l2/src/main/java/com/tc/services/LocalMonitoringProducer.java
dso-l2/src/main/java/com/tc/services/PlatformServiceProvider.java
dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistryImpl.java
dso-l2/src/test/java/com/tc/objectserver/testentity/TestEntityServer.java
dso-l2/src/test/java/com/tc/server/TestServiceProvider.java
pom.xml

* Add ClientStatePersistor, EntityPersistor, TransactionOrderPersistor and ClusterStatePersistor state to cluster state
excerpt from a cluster state dump:
--> com.tc.objectserver.persistence.ClusterStatePersistor
--> --> StripeID = StripeID[b6640d6b502a4b36918a773fe10761c1]
--> --> Version = 5.3.0.0.0
--> --> Initial State = null
--> --> Current State = State[ ACTIVE-COORDINATOR ]
--> --> isDBClean = true
--> com.tc.objectserver.persistence.EntityPersistor
--> --> Existing entities: 
--> --> --> org.terracotta.entity.testsupport.TestSupport:TestSupport
--> --> Client Journals: 
--> --> Next consumer ID = 2
--> com.tc.objectserver.persistence.ClientStatePersistor
--> --> Connected clients: 
--> --> --> ClientID[0]
--> --> Next client id: 1
--> …

Adapt to CommonServerEntity and ServiceProvider API changes

---

dso-l1/src/main/java/com/tc/object/config/ConnectionInfoConfig.java
dso-l2/src/test/java/com/tc/config/PortBindAddressTest.java
dso-l2/src/test/java/com/tc/config/schema/ConfigDefaultPortTest.java
dso-l2/src/test/java/com/tc/config/schema/setup/BaseConfigurationSetupManagerTest.java
pom.xml

Should follow https://github.com/Terracotta-OSS/terracotta-configuration/pull/58 merge 
Note that 
- there are still some tests which references 9510 port (or other default port numbers) but they are explicitly configured in the test xml or code. 
- ConnectionInfoConfig still uses hardcoded tsa port as dso-l1 doesn't depend on terracotta-configuration, would like discuss internally before adding that dependency
- ConnectionInfoConfig's code that references hardcoded tsa port looks like a dead code but we need this dependency change for Terracotta-OSS/terracotta-core#549

Adapt tc config default port changes

---

dso-l2/src/main/java/com/tc/objectserver/entity/ClientDescriptorImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistryImpl.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
dso-l2/src/test/java/com/tc/objectserver/testentity/TestEntityServer.java
pom.xml

Implementation to allow an entity, passive or active, to track
messages. Both active and passive invoke methods now supply
ClientDescriptor and current/oldest transaction id's, as well as
message.
invoke() became invokeActive(0 and invokePassive(), to differentiate
between the active and passive code paths.

APIs Issue 227: Message Tracking support

---

dso-l2/src/main/java/com/tc/objectserver/entity/ClientDescriptorImpl.java
dso-l2/src/main/java/com/tc/objectserver/entity/InvokeContextImpl.java
dso-l2/src/test/java/com/tc/objectserver/entity/ClientDescriptorImplTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/InvokeContextImplTest.java
dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
pom.xml
tc-messaging/src/main/java/com/tc/net/ClientID.java
tc-messaging/src/main/java/com/tc/object/ClientInstanceID.java

Actually, I had to add Serializable to ClientDescriptor and
ClientInstanceID. Also, InvokeContextImpl takes ClientDescriptorImpl
as an argument, not ClientDescriptor; this allowed for the
implementation of isClientInformationValid() on InvokeContext,
to better handle HA/MessageTracker cases.

APIs Issue 237: Add Serializable to ClientDescriptor

---

dso-l2/src/main/java/com/tc/objectserver/entity/InvokeContextImpl.java

The eldest txid should not contribute to the validity of the client
info.

Issue 609: Fix for InvokeContextImpl client info test method

---

terracotta-kit/pom.xml

logback-core and slf4j will be pulled as transitive dependencies.

Fix logging dependencies of kit

---

common/src/main/java/com/tc/tracing/Trace.java
dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
dso-l1/src/main/java/com/tc/object/InFlightMessage.java
dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
dso-l2/src/main/java/com/tc/objectserver/api/ServerEntityRequest.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java

Creating this PR to discuss traceability in more detail, this work is in very early stage and lot of code polishing is needed. 
**Notes**
- ClientID:TranscationID is used to track a particular message
- Not all code paths are covered. 
**Sample output**
```
➜  system-tests git:(master) ✗ grep 'trace - 1:2' target/test-classes/testing_directory/org.terracotta.kit_testing.GalvanDumperTest/OneActive/client0/stdout.log
2017-07-11 17:31:32,321 [main] INFO com.tc.tracing.Trace - [trace - 1:2] start trace for componentName - ClientEntityManagerImpl.invokeAction
2017-07-11 17:31:32,321 [main] INFO com.tc.tracing.Trace - [trace - 1:2] InFlightMessage - Received ACK: SENT
2017-07-11 17:31:32,321 [main] INFO com.tc.tracing.Trace - [trace - 1:2] ClientEntityManagerImpl.invokeAction - …
```

Prototype for traceability

---

common/src/main/java/com/tc/tracing/Trace.java
dso-l2/src/main/java/com/tc/objectserver/api/Retiree.java
dso-l2/src/main/java/com/tc/objectserver/entity/AbstractServerEntityRequestResponse.java
dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/RetirementManager.java
dso-l2/src/main/java/com/tc/services/EntityMessengerService.java

Tracing deferred messages is possible now. 
➜  system-tests git:(master) ✗ grep Deferring target/test-classes/testing_directory/org.terracotta.kit_testing.GalvanEntityMessengerTest/OneActive/stripe0/testServer0/stdout.log
2017-07-14 19:00:39,851 [WorkerThread(request_processor_stage, 7, 7)] INFO com.tc.tracing.Trace - [0:5] ManagedEntityImpl.invoke:invokeActive - Deferring retirement for GrabBagMessage{op=org.terracotta.entity.grabbag.PostAsyncMessageOperation@666fa268} until GrabBagMessage{op=org.terracotta.entity.grabbag.OneStringOperation@18dd227b} is finished
➜  system-tests git:(master) ✗ grep 'GrabBagMessage{op=org.terracotta.entity.grabbag.OneStringOperation@18dd227b}' target/test-classes/testing_directory/org.terracotta.kit_testing.GalvanEntityMessengerTest/OneActive/stripe0/testSe …

Add tracing for deferred messages

---

dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/services/MappedStateCollector.java
pom.xml

updated the PR with new terracotta-configuration 10.3.0-pre13 release

Fix #613: Add extended configurations state to cluster state dump

---

terracotta-kit/src/assemble/server/bin/start-tc-server.sh

1. Made the start-tc-server.sh script adapt to space characters in path.
2. Minor formatting changes.

Issue#652: Fixed start-tc-server.sh so that it handles spaces in path

---

dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java

As Abhilash points out, the concurrency key is not useful for this equality check.

Use only target passives in equality for passive synch channels

---

dso-l2/src/main/resources/logback.xml
galvan-support/src/main/java/org/terracotta/testing/rules/BasicExternalCluster.java
galvan-support/src/main/java/org/terracotta/testing/rules/BasicExternalClusterBuilder.java
galvan-support/src/test/java/org/terracotta/testing/rules/SimpleActivePassiveWithClassRuleIT.java
galvan-support/src/test/resources/custom-logback-ext.xml
pom.xml
terracotta-kit/src/assemble/server/lib/logback-ext.xml

This `logback-ext.xml` is intended to be used by developers. This file is packaged as part of the kit and is documented in itself. If we don't want this file exposed like this we could make it a hidden file and document the existence of such a file elsewhere. Otherwise we could completely avoid packaging this file and have this template also included in the documentation. Not sure what's the best thing to do here. So suggestions welcome.

Configuration extension for server logging

---

dso-l2/src/main/java/com/tc/l2/ha/ChannelWeightGenerator.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/test/java/com/tc/l2/ha/ChannelWeightGeneratorTest.java

active connections should only be weighted in the server is active and the connection is not diagnostic or informational or a redirect.

Fix #730 - Fix election weighting for active connections [master]

---

terracotta-kit/src/assemble/server/bin/start-tc-server.sh

Similar behavior to tc 4.x - if installed via installer, use the installer JVM

Setting JAVA_HOME via installer setenv if available

---

common/src/main/java/com/tc/runtime/TCMemoryManagerImpl.java
common/src/main/java/com/tc/runtime/TCMemoryManagerJdk15PoolMonitor.java
terracotta-kit/src/assemble/server/bin/start-tc-server.bat
terracotta-kit/src/assemble/server/bin/start-tc-server.sh

Also update the max direct memory value used on command line, IBM VM no
longer parses 2^63-1 properly

[release/5.3] Issue #794 Degrade when memory pools not identified

---

dso-l1/src/main/java/com/tc/object/ClientBuilderFactory.java

classloading issue: 
an instance of com.terracottatech.store.StoreException <java.util.ServiceConfigurationError: com.tc.object.ClientBuilderFactory: Provider com.tc.object.StandardClientBuilderFactory not a subtype> is a java.util.ServiceConfigurationError
Stacktrace was: java.util.ServiceConfigurationError: com.tc.object.ClientBuilderFactory: Provider com.tc.object.StandardClientBuilderFactory not a subtype
at java.util.ServiceLoader.fail(ServiceLoader.java:239)
at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
at com.tc.object.ClientBuilderFactory.get(ClientBuilderFactory.jav …

Fix OSGI classloading issue with ClientBuilderFactory

---

build-parent/pom.xml
dso-l1/pom.xml
dso-l1/src/main/java/com/tc/object/handshakemanager/ClientHandshakeManagerImpl.java
dso-l1/src/test/java/com/tc/object/handshakemanager/ClientHandshakeManagerTest.java

* Write info message to client log if versions are different but no
error is thrown.
* Added unit tests, upgraded powermock to 1.6.1.

protect against client-server version/protocol mismatch

---

build-parent/pom.xml
terracotta-kit/src/assemble/voter/bin/base-voter.bat
terracotta-kit/src/assemble/voter/bin/base-voter.sh
terracotta-kit/src/assemble/voter/bin/start-tc-voter.bat
voter/src/main/java/org/terracotta/voter/ActiveVoter.java
voter/src/main/java/org/terracotta/voter/ClientVoterManager.java
voter/src/main/java/org/terracotta/voter/ClientVoterManagerImpl.java
voter/src/main/java/org/terracotta/voter/TCVoterImpl.java
voter/src/main/java/org/terracotta/voter/TCVoterMain.java
voter/src/test/java/org/terracotta/voter/TCVoterMainTest.java
voter/src/test/resources/tc-config.xml

The original voter script was split into two: a base script with most of the original content + the main script that just passes the main method name to be executed to the base script. This facilitates the reuse of the base script by extensions.

TCVoter refactoring for extensions

---

connection-impl/src/main/java/com/terracotta/connection/TerracottaConnection.java
pom.xml

This is the only place I think we need, but I may be wrong.
So I think as and when we find some more places, we replace Illegalstates with `ConnectionShutdownException` or `ConnectionClosedException`, which ever fits/suits

New exception for shutdown connections #845

---

galvan-support/pom.xml
galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterFOPConsistencyVoterIT.java
voter/src/main/java/org/terracotta/voter/TCVoterImpl.java

TCVoterImpl.register was failing with an `AssertionError: Received invalid config from server` while parsing the server config.
The changes in this PR eliminates the need for parsing tc-configs from the target servers.

TCVoterImpl.register to handle just a single stripe

---

common/src/main/java/com/tc/async/impl/EventCreator.java
common/src/main/java/com/tc/async/impl/StageImpl.java
common/src/main/java/com/tc/net/protocol/tcm/AbstractMessageChannel.java
common/src/main/java/com/tc/net/protocol/transport/ConnectionIDFactory.java
common/src/main/java/com/tc/net/protocol/transport/NullConnectionIDFactoryImpl.java
common/src/main/java/com/tc/properties/TCPropertiesConsts.java
dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/main/java/com/tc/objectserver/handler/VoltronMessageHandler.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/objectserver/persistence/ClientStatePersistor.java
dso-l2/src/main/java/com/tc/objectserver/persistence/Persistor.java
dso-l2/src/test/java/com/tc/objectserver/persistence/PersistorTest.java

Orphaned clients should not re-register themselves and reconnect
Add TCProperty to force single-threaded operation.

Fix orphaned clients 

---

common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
common/src/main/java/com/tc/net/protocol/transport/ServerStackProvider.java
dso-l2/src/main/java/com/tc/objectserver/impl/ChannelStatsImpl.java
galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterFOPConsistencyVoterIT.java

Diagnostic clients must use this connection and cannot be blocked.

Redirects are only advisory not handshake error. 

---

common/src/main/java/com/tc/properties/TCPropertiesConsts.java
common/src/main/java/com/tc/util/version/VersionCompatibility.java
common/src/main/resources/com/tc/properties/tc.properties
common/src/test/java/com/tc/util/version/VersionCompatibilityTest.java
dso-l1/src/main/java/com/tc/object/handshakemanager/ClientHandshakeManagerImpl.java
dso-l1/src/test/java/com/tc/object/handshakemanager/ClientHandshakeManagerTest.java
dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/objectserver/impl/ServerPersistenceVersionChecker.java
dso-l2/src/test/java/com/tc/net/groups/TCGroupManagerImplTest.java
dso-l2/src/test/java/com/tc/objectserver/impl/ServerPersistenceVersionCheckerTest.java

Completely disabled version compatibility checks in code. Removed configuration. Left the VersionCompatibility class and its test as they are (can we deprecate?)

Disable version compatibility check.

---

dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/services/PlatformConfigurationImpl.java
pom.xml

Implemented changes in PlatformConfiguration interface towards providing server host and port information.
Depends on https://github.com/Terracotta-OSS/terracotta-apis/pull/293 and a corresponding version bump.

Changes in PlatformConfiguration interface to provide host and port

---

common/src/main/java/com/tc/net/protocol/tcm/CommunicationsManagerImpl.java
common/src/main/java/com/tc/net/protocol/tcm/NetworkListener.java
common/src/main/java/com/tc/net/protocol/tcm/NetworkListenerImpl.java
common/src/main/java/com/tc/net/protocol/transport/ServerStackProvider.java
common/src/test/java/com/tc/net/core/NoReconnectThreadTest.java
common/src/test/java/com/tc/net/core/OOOReconnectTimeoutTest.java
common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java
common/src/test/java/com/tc/net/protocol/tcm/LazyHandshakeTest.java
common/src/test/java/com/tc/net/protocol/tcm/MessageChannelTest.java
common/src/test/java/com/tc/net/protocol/tcm/NetworkListenerTest.java
common/src/test/java/com/tc/net/protocol/transport/ConnectionHealthCheckerReconnectTest.java
dso-l2/src/main/java/com/tc/l2/ha/ClusterStateImpl.java
dso-l2/src/main/java/com/tc/l2/ha/StripeIDStateManagerImpl.java
dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
dso-l2/src/main/java/com/tc/objectserver/persistence/ClusterStatePersistor.java
dso-l2/src/test/java/com/tc/net/protocol/transport/ServerStackProviderTest.java

cherry-picked from master a4768fbca9ae7f08cff4a32553f6b79065b3e0f7
Conflicts:
common/src/main/java/com/tc/net/protocol/transport/ServerStackProvider.java
dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java

Fix #939 - Reconnect needs to rebuild with ConnectionID not ClientID

---

dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
tc-messaging/src/main/java/com/tc/entity/LinearVoltronEntityMultiResponse.java

Fastpath is no longer valid for multisend response since multi-threaded access is possible to addSequentially

Merge fix fastpath

---

dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
pom.xml

Fix an assertion when server generated messages are sent to a client
update galvan version
add back direct execution optimization to addSequentially

Only send back messages to the client that originated from the client

---

common/src/main/java/com/tc/properties/TCPropertiesConsts.java
common/src/main/java/com/tc/runtime/GcMonitor.java
common/src/main/java/com/tc/runtime/TCRuntime.java
common/src/main/resources/com/tc/properties/tc.properties

Similar to the stages monitoring, this patch will log GC activity and heap occupation every few seconds.
I am not certain we want this in the server, so I have no hard feelings if you don't want to merge this. But this logs the basics to quickly help us figure out if the GC is healthy or not, and if the heap is reasonably sized.

add gc monitoring

---

dso-l2/src/test/java/com/tc/config/DefaultConfigurationProviderTest.java
terracotta-kit/src/assemble/server/bin/start-tc-server.bat
terracotta-kit/src/assemble/server/bin/windowsBatchCoding.adoc

This commit stream corrects behavior of `start-tc-server.bat` when installed in a directory path containing special characters -- like parentheses.  It also includes corrections to `DefaultConfigurationProviderTest` for failures that occur when built under Windows.

Correct behavior of start-tc-server.bat when installed in directory with special characters

---

dso-l2/src/main/java/com/tc/l2/ha/RandomWeightGenerator.java
dso-l2/src/main/java/com/tc/l2/ha/ServerUptimeWeightGenerator.java
dso-l2/src/test/java/com/tc/l2/ha/RandomWeightGeneratorTest.java
dso-l2/src/test/java/com/tc/l2/ha/ServerUptimeWeightGeneratorTest.java
galvan-support/src/test/java/org/terracotta/testing/rules/ClientLeakIT.java

Split-brain resolution through zap of peer actives needs adjustment as both actives can believe they are the winner due to non-deterministic weights.

Zap weights [MASTER]

---

galvan-support/pom.xml

Fixes Issue #1100 by running preventing JVM reuse for integration tests in the galvan-support module.

Correct intermittent failure of ClientLeakIT.testConnectionMakerDiesWithNoRef

---

dso-l2/src/main/java/com/tc/server/TCServerImpl.java

When a server is shut down or restarted programmatically, all we log is `L2 Exiting...`, which doesn't make it clear if the shutdown was intentional or not. The logging statement added here helps the users, and test frameworks to ascertain that the server was shut down.

Added console logging for server restart event

---

default-configuration/src/main/java/org/terracotta/config/provider/DefaultConfigurationProvider.java
default-configuration/src/test/java/org/terracotta/config/provider/DefaultConfigurationProviderTest.java
dso-l2/src/main/java/com/tc/l2/state/ServerVoterManagerImpl.java
dso-l2/src/test/java/com/tc/l2/state/ServerVoterManagerImplTest.java
galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalConsistencyIT.java

Override votes will be reset on every state change on vote start.  Because of this, overrides should always be accepted so clients can connect to servers that have active mode only because of overridden status.

Override votes should always be accepted

---

galvan-support/src/main/java/org/terracotta/testing/config/DefaultStartupCommandBuilder.java

Galvan-based tests are failing on Windows -- unable to start the server because the start-tc-server.bat command cannot be found.  The cause is need in Windows for a normalized, absolute path to the script.  This update both resolves the script path against the server working directory and normalizes it, and then quotes the path to avoid issues with interesting path characters.

Correct Galvan-based test failures on Windows

---

build-parent/pom.xml
common/pom.xml
dso-l2/pom.xml
galvan-support/pom.xml
pom.xml
terracotta-kit/pom.xml
terracotta/pom.xml

latest terracotta-parent, using maven-forge-plugin for full test jvm from toolchains support.  All references for surefire and failsafe are removed (forge plugin is a superset of both).

new parent, surefire/failsafe->forge

---

.gitattributes
test-common/src/main/java/com/tc/test/BaseScriptTest.java

Restores successful Windows builds

Handle UnsupportedOperationException from Files.setPosixFilePermissions

---

dso-l1/src/main/java/com/tc/object/StandardClientBuilderFactory.java
voter/src/main/java/org/terracotta/voter/ActiveVoter.java
voter/src/main/java/org/terracotta/voter/ClientVoterManagerImpl.java
voter/src/test/java/org/terracotta/voter/ActiveVoterTest.java

Voter need to be tolerant of errors in registration 
BufferManagerFactorySupplier should always supply at least a ClearTextBufferManager

small stability items

---

build-parent/pom.xml
connection-impl/pom.xml
pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

common/src/main/java/com/tc/util/version/Version.java
common/src/main/java/com/tc/util/version/VersionCompatibility.java
common/src/test/java/com/tc/util/version/VersionTest.java
tc-server/src/main/java/com/tc/objectserver/handler/ClientHandshakeHandler.java

Noticed that VersionCompatibility contained a bug when comparing against an older version that possesses a greater minor or micro value.  For Example: 10.3.1.4.11 was identified as being greater than 10.7.0.

Fixing bug in version compatibility check

---

common/src/main/java/com/tc/object/msg/TestClientHandshakeMessage.java
management/src/main/java/com/tc/management/beans/TCServerInfoMBean.java
tc-client/src/main/java/com/tc/object/ClientBuilder.java
tc-client/src/main/java/com/tc/object/DistributedObjectClient.java
tc-client/src/main/java/com/tc/object/StandardClientBuilder.java
tc-client/src/main/java/com/tc/object/handshakemanager/ClientHandshakeManagerImpl.java
tc-client/src/test/java/com/tc/object/handshakemanager/ClientHandshakeManagerTest.java
tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeMessage.java
tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeMessageFactory.java
tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeMessageImpl.java
tc-server/src/main/java/com/tc/management/beans/TCServerInfo.java
tc-server/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
tc-server/src/main/java/com/tc/objectserver/handshakemanager/ClientHandshakeMonitoringInfo.java
tc-server/src/main/java/com/tc/objectserver/handshakemanager/ClientHandshakePrettyPrintable.java
tc-server/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
tc-server/src/main/java/com/tc/server/TCServer.java
tc-server/src/main/java/com/tc/server/TCServerImpl.java
tc-server/src/main/java/com/tc/stats/Client.java
tc-server/src/main/java/com/tc/stats/DSO.java
tc-server/src/main/java/com/tc/stats/api/ClientMBean.java
tc-server/src/main/java/com/tc/stats/api/DSOMBean.java
tc-server/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java

Connected client versioning information, (e.g. version and revision), needs to be retrievable by the Diagnostic Service.  The current changes include (1) ability for connecting clients to provide their build revision string as part of the connection handshake and (2) the client version details exposed via the existing DSO MBean.,

Add client revision to handshake info and TCServerInfo mbean.

---

common/src/main/java/com/tc/net/protocol/tcm/ChannelManagerImpl.java
common/src/main/java/com/tc/net/protocol/tcm/CommunicationsManager.java
common/src/main/java/com/tc/net/protocol/tcm/CommunicationsManagerImpl.java
common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
common/src/main/java/com/tc/net/protocol/transport/ConnectionPolicy.java
common/src/main/java/com/tc/net/protocol/transport/ConnectionPolicyImpl.java
common/src/main/java/com/tc/net/protocol/transport/ConnectionWatcher.java
common/src/main/java/com/tc/net/protocol/transport/MessageTransportBase.java
common/src/main/java/com/tc/net/protocol/transport/NullConnectionPolicy.java
common/src/main/java/com/tc/net/protocol/transport/ServerMessageTransport.java
common/src/main/java/com/tc/net/protocol/transport/ServerStackProvider.java
common/src/main/java/com/tc/object/net/DSOChannelManagerImpl.java
common/src/test/java/com/tc/net/core/NoReconnectThreadTest.java
common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java
common/src/test/java/com/tc/net/protocol/tcm/ChannelManagerImplTest.java
common/src/test/java/com/tc/net/protocol/tcm/LazyHandshakeTest.java
common/src/test/java/com/tc/net/protocol/tcm/MessageChannelTest.java
common/src/test/java/com/tc/net/protocol/tcm/NetworkListenerTest.java
galvan-support/pom.xml
tc-server/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
tc-server/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
tc-server/src/test/java/com/tc/net/groups/TCGroupMessageWrapperTest.java
tc-server/src/test/java/com/tc/net/protocol/tcm/TestCommunicationsManager.java
tc-server/src/test/java/com/tc/net/protocol/transport/ServerStackProviderTest.java

During reconnect the low-level tc-connection from the client is inserted into a pre-prepared network stack.  If the connection fails to complete handshake or the client abandons the connection attempt, the server tears down the network stack and the client will never connect.  This change will allow a client to restart the process during the reconnect window and attempt to make and bootstrap a successful connection.

Reconnect change

---

common/src/main/java/com/tc/net/protocol/ClientNetworkStackHarness.java
common/src/main/java/com/tc/net/protocol/tcm/ClientMessageChannelImpl.java
common/src/main/java/com/tc/net/protocol/tcm/CommunicationsManagerImpl.java
common/src/main/java/com/tc/net/protocol/tcm/MessageTransportFactoryImpl.java
common/src/main/java/com/tc/net/protocol/transport/ClientConnectionEstablisher.java
common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
common/src/main/java/com/tc/net/protocol/transport/ConnectionWatcher.java
common/src/main/java/com/tc/net/protocol/transport/MessageTransportFactory.java
common/src/test/java/com/tc/net/protocol/transport/ClientConnectionEstablisherTest.java
tc-server/src/main/java/com/tc/server/BootstrapThrowableHandler.java

failure scenario is:
1. active dies triggering failover.
2. client connect but handshake times out
3. underlying connection is closed triggering another reconnect request
4. reconnect threads locks on itself waiting for itself to die
The patch fixes this by only scheduling a new reconnect if the connection close occurs on a different thread

fix infinite loop in reconnect timeout

---

tc-server/src/main/java/com/tc/objectserver/api/EntityManager.java
tc-server/src/main/java/com/tc/objectserver/api/ManagedEntity.java
tc-server/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
tc-server/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
tc-server/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
tc-server/src/main/java/com/tc/objectserver/entity/ServerEntityFactory.java
tc-server/src/main/java/com/tc/objectserver/handler/EntityExistenceHelpers.java
tc-server/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
tc-server/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
tc-server/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
tc-server/src/test/java/com/tc/objectserver/handler/EntityExistenceHelpersTest.java
tc-server/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java

For this change, the logic for determining if an entity can be deleted is based on whether or not the entity is a PermanentEntity.  The previous approach determined an entity's deletion status based on whether or not the entity creation requestor was a client.  That approach did not work for dynamic scaling whereby entities can be created by non-clients (i.e. the server itself).

fix canDelete logic when creating entities

---

common/src/main/java/com/tc/net/protocol/tcm/NetworkListener.java
common/src/main/java/com/tc/net/protocol/tcm/NetworkListenerImpl.java
common/src/main/java/com/tc/properties/TCPropertiesImpl.java
common/src/main/java/com/tc/util/properties/TCPropertyStore.java
galvan-support/src/test/java/org/terracotta/functional/DirectConnectIT.java
galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterActivePassiveIT.java
tc-server/src/main/java/com/tc/l2/state/ConsistencyManager.java
tc-server/src/main/java/com/tc/l2/state/SafeStartupManagerImpl.java
tc-server/src/main/java/com/tc/l2/state/ServerVoterManagerImpl.java
tc-server/src/main/java/com/tc/l2/state/StateManagerImpl.java
tc-server/src/main/java/com/tc/objectserver/impl/DiagnosticsHandler.java
tc-server/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
tc-server/src/main/java/com/tc/server/TCServerImpl.java
tc-server/src/test/java/com/tc/l2/state/ConsistencyManagerImplTest.java
tc-server/src/test/java/com/tc/l2/state/SafeStartupManagerImplTest.java
tc-server/src/test/java/com/tc/server/TCServerImplTest.java
voter/src/main/java/org/terracotta/voter/ClientVoterManagerImpl.java

The server can report that it is accepting clients when the listening port is not bound but the rest of the stack is built.  Only report that clients are being accepted once the TSA is bound to the socket listener.  
Also fixed is NPE errors when the server is checked for state before being started.

Fix listening timing hole

---

build-parent/pom.xml
connection-impl/pom.xml
pom.xml

In addition to bumping the version of terracotta-utilities used,
this commit reduces the repositories and pluginRepositories elements
to those required to locate the direct dependencies of this project.
More specifically, the SNAPSHOT repositories are removed -- inclusion
of SNAPSHOT repositories interferes with the use of range-based version
specifications.  Should a developer want to include a SNAPSHOT release
in a build, local addition of the SNAPSHOT repositories can be employed.

Remove POM repositories elements & bump terracotta-utilities version

---

build-parent/pom.xml
common/pom.xml
galvan-support/pom.xml
pom.xml
tc-client/pom.xml
terracotta-kit/pom.xml

This commit introduces version ranges for Logback and SLF4J.
This commit also introduces a version range for terracotta-utilities
and bumps the base version.  The upper bound is left open.
To prevent depdendency convergence conflicts, several exclusions
(mostly for SLF4J) are also included.

Use version range for logging components & terracotta-utilities

---

tc-messaging/src/main/java/com/tc/io/TCByteBufferInputStream.java

due to improper use of byte buffers after recycle

[DAGGY] revert optimization that causes data corruption 

---

common/src/main/java/com/tc/net/basic/BasicConnection.java
common/src/main/java/com/tc/net/basic/BasicConnectionManager.java
common/src/main/java/com/tc/net/core/TCConnectionImpl.java
common/src/main/java/com/tc/net/core/TCConnectionManager.java
common/src/main/java/com/tc/net/core/TCConnectionManagerImpl.java
common/src/main/java/com/tc/net/protocol/tcm/NetworkListenerImpl.java
common/src/main/java/com/tc/net/protocol/tcm/TCMessageParser.java
common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
common/src/main/java/com/tc/net/protocol/transport/MessageTransportBase.java
common/src/test/java/com/tc/net/basic/BasicConnectionTest.java
common/src/test/java/com/tc/net/core/NoReconnectThreadTest.java
common/src/test/java/com/tc/net/core/TCConnectionImplTest.java
common/src/test/java/com/tc/net/core/TCConnectionManagerTest.java
common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java
common/src/test/java/com/tc/net/protocol/tcm/MessageChannelTest.java
galvan-support/src/test/java/org/terracotta/testing/rules/DynamicPassiveRemovalIT.java
tc-messaging/src/main/java/com/tc/io/TCByteBufferInput.java
tc-messaging/src/main/java/com/tc/io/TCByteBufferInputStream.java
tc-messaging/src/main/java/com/tc/net/core/TCConnection.java
tc-messaging/src/main/java/com/tc/net/protocol/TCNetworkMessage.java
tc-messaging/src/main/java/com/tc/net/protocol/TCNetworkMessageImpl.java
tc-messaging/src/main/java/com/tc/net/protocol/tcm/TCActionImpl.java
tc-server/src/main/java/com/tc/objectserver/impl/DiagnosticsHandler.java
tc-server/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
tc-server/src/test/java/com/tc/net/groups/TCGroupMessageWrapperTest.java

This prevents data corruption when reading from the network by delaying buffer recycle until after hydrate of a TCAction has occurred.

More data corruption

---

tc-messaging/src/main/java/com/tc/net/protocol/transport/WireProtocolAdaptorImpl.java

with the added message recall feature, it is possible for a message group to start with multiple messages and get reduced to one message because all others have been recalled.  remove assert as this is a completely valid case

remove an assert that is not longer valid.  

---

common/src/main/java/com/tc/net/protocol/tcm/CommunicationsManagerImpl.java
common/src/main/java/com/tc/net/protocol/tcm/MessageTransportFactoryImpl.java
common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
common/src/main/java/com/tc/net/protocol/transport/ConnectionHealthCheckerContextImpl.java
common/src/main/java/com/tc/net/protocol/transport/DisabledHealthCheckerConfigImpl.java
common/src/main/java/com/tc/net/protocol/transport/HealthCheckerConfig.java
common/src/main/java/com/tc/net/protocol/transport/HealthCheckerConfigClientImpl.java
common/src/main/java/com/tc/net/protocol/transport/HealthCheckerConfigImpl.java
common/src/main/java/com/tc/net/protocol/transport/MessageTransport.java
common/src/main/java/com/tc/net/protocol/transport/MessageTransportBase.java
common/src/main/java/com/tc/net/protocol/transport/ServerStackProvider.java
common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java
common/src/test/java/com/tc/net/protocol/transport/CallbackPortRangeTest.java
common/src/test/java/com/tc/net/protocol/transport/ClientConnectionEstablisherTest.java
common/src/test/java/com/tc/net/protocol/transport/ClientMessageTransportTest.java
tc-messaging/src/main/java/com/tc/net/protocol/transport/TransportHandshakeMessageFactory.java
tc-messaging/src/main/java/com/tc/net/protocol/transport/TransportMessageFactoryImpl.java
tc-messaging/src/test/java/com/tc/net/protocol/transport/TransportHandshakeMessageTest.java

Removing handshake negotiated callback ports.  They don't work in heterogeneous networks such as when using containers.  Clients will still try and do socket connects as a last ditch effort to test server liveliness.  Servers will never try and socket connect clients.

Remove callback port useage

---

common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
common/src/main/java/com/tc/net/protocol/transport/MessageTransportBase.java
common/src/main/java/com/tc/net/protocol/transport/MessageTransportState.java
common/src/main/java/com/tc/net/protocol/transport/MessageTransportStatus.java
common/src/main/java/com/tc/net/protocol/transport/ServerMessageTransport.java
common/src/main/java/com/tc/net/protocol/transport/ServerStackProvider.java
common/src/test/java/com/tc/net/protocol/transport/ServerMessageTransportTest.java
galvan-support/src/test/java/org/terracotta/functional/ReconnectRejectIT.java
management/src/main/java/com/tc/management/beans/TCServerInfoMBean.java
tc-client/src/main/java/com/tc/object/DistributedObjectClient.java
tc-client/src/main/java/com/tc/object/handshakemanager/ClientHandshakeManagerImpl.java
tc-client/src/test/java/com/tc/object/ClientEntityManagerTest.java
tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeMessage.java
tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeMessageFactory.java
tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeMessageImpl.java
tc-server/src/main/java/com/tc/management/beans/TCServerInfo.java
tc-server/src/main/java/com/tc/objectserver/handler/ClientHandshakeHandler.java
tc-server/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java

The server can only handle one connection per client.  There is no reconnection allowed outside the reconnect window.  Prevent clients from trying to reconnect with a previously connected server at both the transport layer as well as secondary handshake.  The instances of using the secondary handshake check should be zero but add this code as a sanity check and it does not break protocol and is good to have the added information during secondary handshake

fixes to prevent client reconnection outside the server's reconnect window

---

azure-pipelines.yml
galvan/build.gradle
gradle.properties
tc-server/src/main/java/com/tc/l2/ha/ReplicatedClusterStateManagerImpl.java

Replicated cluster state messages don't do anything with replies so here they are just erased as they are not needed.

replicated cluster state no longer replies
