Terracotta-OSS/terracotta-core

- build-parent/pom.xml
- pom.xml
* Bump to latest parent pom version
* Rename root artifact to terracotta-core-root
* Update scm info
> Misc. pom updates

- dso-l2/src/main/java/com/tc/l2/handler/L2StateChangeHandler.java
- dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
- dso-l2/src/main/java/com/tc/objectserver/core/api/ITopologyEventCollector.java
- dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ClientEntityStateManager.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ClientEntityStateManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ChannelLifeCycleHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ClientEntityStateManagerImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
Created ITopologyEventCollector as an interface describing what data we collect and ManagementTopologyEventCollector as a very basic starting-point of a data collector implementation.
> Collect and verify monitoring data related to network topology and entity life cycle

- common/pom.xml
- common/src/main/java/com/tc/classloader/ComponentURLClassLoader.java
- common/src/test/java/com/tc/classloader/CommonComponentClass.java
- common/src/test/java/com/tc/classloader/ComponentURLClassLoaderTest.java
- common/src/test/java/com/tc/classloader/SpecificComponentClass.java
to handle CommonComponent annotation.  Add a test case.
> Fix #17 - component class loader needs proper decision making

- .gitignore
- common/src/main/java/com/tc/classloader/ServiceLocator.java
- common/src/test/java/com/tc/classloader/ServiceLocatorTest.java
- common/src/test/java/com/tc/classloader/TestInterface.java
- common/src/test/java/com/tc/classloader/TestInterfaceImpl.java
to every parent class loader provided
> Fix #38 - Fix ServiceLocator by making the api class loader common

- client-runtime/pom.xml
- connection-impl/pom.xml
- connection-loader/pom.xml
- connection-loader/src/main/java/com/terracotta/connection/CreateClient.java
- pom.xml
- terracotta-kit/pom.xml
- terracotta-kit/src/assemble/distribution.xml
Created a fat jar with required runtime dependencies on client side and tested with test entites.
> fix #44 - create client runtime jar and include in the terracotta-kit

- dso-l2/src/main/java/com/tc/objectserver/core/api/ITopologyEventCollector.java
- dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ChannelLifeCycleHandler.java
- dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java
This means that this change depends on Terracotta-OSS/terracotta-apis#36
> Issue 46: Uses the new platform monitoring types and constants

- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
simple fix and some logging changes
> Fix #52 - Acknowledge deferred actions

- connection-impl/src/main/java/com/terracotta/connection/entity/MaintenanceModeService.java
- connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java
- connection-impl/src/test/java/com/terracotta/connection/entity/TerracottaEntityRefTest.java
-this required an update to MaintenanceModeService to expose the tryLock() in the underlying lock manager
-note that this will fail the same was as calling destroy() if the connection already has a read-lock on the entity
> Fix #60: Implement EntityRef.tryDestroy() in TerracottaEntityRef

- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
Stored message need to use the correct default key
> quick fix for Issue #47

- connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java
- dso-l1/src/main/java/com/tc/object/ClientEntityManager.java
- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
- dso-l2/src/main/java/com/tc/objectserver/api/ServerEntityAction.java
- dso-l2/src/main/java/com/tc/objectserver/entity/AbstractServerEntityRequest.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
- dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityFactory.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/EntityPersistor.java
- dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
- tc-messaging/src/main/java/com/tc/entity/VoltronEntityMessage.java
- tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java
Follows API changes at Terracotta-OSS/terracotta-apis#48.
Bug fixes to the managed entity deferment queue
> Move codec accessor

- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
The last fix was improper.  Deferred messages need to be inline appended to the end of the sync entity key call.  The previous fix put the messages at the end of the line which could cause out of order execution.  Fix the implementation and add a unit test for the implementation.
> Fix #112 - Add unit test and fix implementation. 

- dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
I am going to merge this as it is a critical fix for passive sync execution.  
Moves sync key start inline on replicated transaction handler thread.
send acknowledge messages to active during sync for entities that have not been sync'd yet
prime and wait for acknowledgment before continuing with replication and sync
> Fix #119 - Passive sync timing fixes

- common/src/main/java/com/tc/properties/TCPropertiesConsts.java
- common/src/main/resources/com/tc/properties/tc.properties
- common/src/test/java/com/tc/util/TCPropertiesConstsTest.java
- dso-l1/src/main/java/com/tc/object/ClientConfigurationContext.java
- dso-l1/src/main/java/com/tc/object/ClientEntityManager.java
- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
- dso-l2/src/main/java/com/tc/management/beans/TCServerInfo.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupMemberDiscoveryStatic.java
- dso-l2/src/main/java/com/tc/net/utils/L2Utils.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFilePersistentStorage.java
Added additional state information for debugging if handshake assert is hit.
Cleaned up some asserts that weren't being thrown
Cleaned up ClientEntityManager thread creation and usage.  Fixed semaphore usage on sent messages
> Handshake cleanup

- dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
failing test due to implementation change
> Fix ClientEntityManagerImplTest

- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
semaphore permits can get drained for sent requests that get lost during reconnect
> reset sent requests semaphore on reconnects

- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
pre-mature fix to semaphore.  Fix for now.  Will create an issue to investigate further
> reverse bogus semaphore reset

- dso-l2/src/main/java/com/tc/l2/handler/L2StateChangeHandler.java
- dso-l2/src/main/java/com/tc/l2/handler/PlatformInfoRequestHandler.java
- dso-l2/src/main/java/com/tc/objectserver/core/api/ITopologyEventCollector.java
- dso-l2/src/main/java/com/tc/objectserver/core/api/ServerConfigurationContext.java
- dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java
- tc-messaging/src/main/java/com/tc/l2/msg/PlatformInfoRequest.java
Create server-to-server communications channel for monitoring support.
Wire server information under the a servers node in the mgmt tree
> Platform monitoring support

- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
messages on a key are improperly being ignored during the sync of the same key
> fix ignore during sync of a key

- common/src/main/java/com/tc/runtime/TCMemoryManagerImpl.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
Some TCThreadGroup threads need better, more efficient shutdown semantics so clients do not wait unnecessarily on shutdown.
TC Memory Monitor is the main culprit in not properly shutting down in a timely fashion.  Fix this by interrupting the thread's idle time.
> Fix #151 - do not delay in interrupting threads

- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageServiceProvider.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformStorageServiceProvider.java
- dso-l2/src/main/java/com/tc/services/BuiltInServiceProvider.java
- dso-l2/src/main/java/com/tc/services/CommunicatorService.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/persistence/FlatFileStorageServiceProviderTest.java
- dso-l2/src/test/java/com/tc/server/TestServiceProvider.java
Updates to account for API changes in Terracotta-OSS/terracotta-apis#66
> Update to account for API issues 58 and 59

- common/src/main/java/com/tc/net/protocol/delivery/OnceAndOnlyOnceProtocolNetworkLayerImpl.java
- common/src/test/java/com/tc/net/protocol/delivery/OnceAndOnlyOnceProtocolNetworkLayerImplTest.java
Client says goodbye.  Server closes sockets.
> Fix #159 - disconnect from the server properly

- common/src/main/java/com/tc/net/protocol/transport/ClientConnectionEstablisher.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/net/groups/TCGroupManagerNodeJoinedTest.java
fix a problem with a node joining test.  Include PASSIVE_SYNCING stage for replication
> Fix #161 - Staging fixup

- common/src/main/java/com/tc/net/protocol/transport/ClientConnectionEstablisher.java
- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
Handshake error needs to clean up connection establisher
Resolve OOO deadlock
> Fix #173 - resolve deadlock 

- terracotta-kit/src/assemble/server/bin/start-tc-server.bat
This pull request is for issue #158 
https://github.com/Terracotta-OSS/terracotta-core/issues/158
> initial import

- terracotta-kit/src/assemble/README.txt
Add some more information about the directories in the kit and add placeholder sections.
> Update readme with placeholders for more informtion

- terracotta-kit/src/assemble/server/bin/start-tc-server.sh
I will get someone to verify this, on Windows, before we can merge.
> Fix #178: Fixed usage of paths with spaces

- dso-l2/src/main/java/com/tc/net/utils/L2Utils.java
- dso-l2/src/test/java/com/tc/net/utils/L2UtilsTest.java
-this fixes some issues where we would ask for 0 threads
> Fix #180: Start thread count at CPU count, not /2

- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
character replacement for windows platforms on lock directory generation
> Fix windows file names.  TAB-6880

- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/services/PlatformServiceImpl.java
- dso-l2/src/main/java/com/tc/services/PlatformServiceProvider.java
* Create PlatformServiceImpl, PlatformServiceProvider and PlatformServiceConfiguration
* Dump Platform State using dumphandler and serverbuilder
> Fix #184 - Implement PlatformService

- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
Throw an EntityException when a client hangs on a closed connection
> Fix#198 - closed connections need to unblock user threads

- dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/api/EntityManager.java
- dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
- dso-l2/src/main/java/com/tc/objectserver/entity/CreateSystemEntityMessage.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
- dso-l2/src/main/java/com/tc/objectserver/handler/EntityExistenceHelpers.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/impl/PermanentEntityParser.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/EntityData.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/EntityPersistor.java
- dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
- dso-l2/src/test/java/com/tc/objectserver/persistence/EntityPersistorTest.java
- tc-messaging/src/main/java/com/tc/l2/msg/PassiveSyncMessage.java
- terracotta/pom.xml
Add the ability to create permanent entities directly from the server.
> Perm entities

- dso-l2/src/main/java/com/tc/objectserver/impl/PermanentEntityParser.java
- dso-l2/src/test/java/com/tc/objectserver/impl/PermanentEntityParserTest.java
leaving out config can cause server crash.
> do null checks for config parsing

- terracotta-kit/src/assemble/distribution.xml
- terracotta-kit/src/assemble/server/bin/start-tc-server.bat
- terracotta-kit/src/assemble/server/bin/start-tc-server.sh
> Fix #213 - terracotta-kit: Move plugins dir to server dir

- terracotta-kit/src/assemble/server/bin/start-tc-server.sh
-sh is aliased to different scripts with different behaviors, depending on the host system and our existing syntax and design most closely matches bash
-this also required removing some special-cases for handing strange wait beheavior we found in sh
> Swtich to bash and remove special-cases for sh work-arounds

- dso-l2/src/main/java/com/tc/objectserver/api/EntityManager.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityFactory.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/impl/PermanentEntityParser.java
- dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistry.java
- dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistryImpl.java
implement builtin entities and services that do not require configuration but are loaded via class path instead of xml config.
> Api issue 109

- common/src/main/java/com/tc/net/protocol/transport/ConnectionHealthCheckerImpl.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
- dso-l1/src/test/java/com/tc/object/DistributedObjectClientTest.java
Separate synchronization for connectionMade and clientStopped
Add notify for health checker stop
Add a test for issue 232 and 233
> Issue 232 & 233

- terracotta-kit/src/assemble/server/bin/start-tc-server.sh
-this was always unreliable and mostly done for the benefit of external tools, such as galvan
-the complexity belongs in those tools, however, and not here
-this change mostly reverts the script to the shape it had in older versions with the exception of some of the recently added white-space handling which is preserved
NOTE:  This should probably merge _after_ Terracotta-OSS/galvan#44
> Fix #237: Remove trap and background process handling

- common/src/main/java/com/tc/config/Directories.java
- dso-l2/src/main/java/com/tc/classloader/ServiceLocator.java
- dso-l2/src/test/java/com/tc/classloader/ServiceLocatorTest.java
- dso-l2/src/test/java/com/tc/classloader/TestLoggingService.java
This PR 
- Updates Directories.java to use new plugins location
- Adds logging to show the plugins api/lib location
- Adds a unit test to verify logging
> Fix #250 - Update Directories.java to use new plugins location

- pom.xml
-<terracotta-apis.version>1.0.1.beta</terracotta-apis.version>
-<terracotta-configuration.version>10.0.1.beta</terracotta-configuration.version>
> Updated release versions of terracotta-apis and terracotta-configuration

- build-parent/pom.xml
- dso-l2/pom.xml
- dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
- dso-l2/src/test/java/com/tc/objectserver/testentity/TestEntity.java
- dso-l2/src/test/java/com/tc/objectserver/testentity/TestEntityServer.java
- dso-l2/src/test/java/com/tc/objectserver/testentity/TestEntityServerService.java
- dso-l2/src/test/resources/META-INF/services/org.terracotta.entity.ServerEntityService
- pom.xml
Added TestEntity since the existing one has been removed from this new version of terracotta-apis.
Also updated the versions of apis and configuration.
> Updated dependencies

- dso-l2/src/main/java/com/tc/objectserver/handler/RetirementManager.java
- dso-l2/src/test/java/com/tc/objectserver/handler/RetirementManagerTest.java
This PR adds 
- support for deferred retirement on multiple messages
- unit tests for retirement using universal keys
> Fix #258: RetirementManager: Add support for deferred retirement on multiple messages

- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
make sure client has been activated before firing a disconnect to topo
> Fix #265 - Assertion Error on client disconnect

- dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
- dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java
- pom.xml
Updated dependencies:
-terracotta-apis.version - 1.0.4.beta
-terracotta-configuration.version - 10.0.4.beta
Also added some tests regarding the new M&M Serializable behavior
> Update dependencies and add monitoring tests

- connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java
- connection-impl/src/test/java/com/terracotta/connection/entity/TerracottaEntityRefTest.java
- pom.xml
method signature changes and destroy call removal
> Fix terracotta-apis#180 - implement non-blocking lifecycle APIs [DO NOT MERGE]

- pom.xml
-terracotta-configuration 10.0.5.beta
> Missed update of config version:

- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/TransactionOrderPersistor.java
- tc-messaging/src/main/java/com/tc/entity/VoltronEntityMultiResponseImpl.java
Small changes to make ProcesssTransactionHandler thread do less work.
> Perf screen

- dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
adds a unit test for getEntity
> add a unit test for getEntity

- dso-l2/src/main/java/com/tc/l2/handler/PlatformInfoRequestHandler.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/services/CommunicatorService.java
- dso-l2/src/main/java/com/tc/services/DelegatingServiceRegistry.java
- dso-l2/src/main/java/com/tc/services/EntityClientCommunicatorService.java
- dso-l2/src/main/java/com/tc/services/EntityMessengerProvider.java
- dso-l2/src/main/java/com/tc/services/EntityMessengerService.java
- dso-l2/src/main/java/com/tc/services/ImplementationProvidedServiceProvider.java
- dso-l2/src/main/java/com/tc/services/PlatformServiceProvider.java
- dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistry.java
- dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistryImpl.java
- dso-l2/src/test/java/com/tc/services/CommunicatorServiceTest.java
- dso-l2/src/test/java/com/tc/services/EntityMessengerProviderTest.java
- tc-messaging/src/main/java/com/tc/l2/msg/PlatformInfoRequest.java
These are a few changes I had to make in support of my #153 prototype and realized that they should probably be merged, before those bigger details are sorted out.
> Registry changes

- dso-l2/src/main/java/com/tc/objectserver/entity/ClientEntityStateManagerImpl.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ChannelLifeCycleHandlerTest.java
Fixes some NPE associated with tests
> fix test failures associated with qa_fixup

- dso-l2/src/main/java/com/tc/l2/handler/L2StateChangeHandler.java
- dso-l2/src/main/java/com/tc/l2/handler/PlatformInfoRequestHandler.java
- dso-l2/src/main/java/com/tc/objectserver/core/api/ITopologyEventCollector.java
- dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/services/LocalMonitoringProducer.java
- dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java
- pom.xml
- tc-messaging/pom.xml
- tc-messaging/src/main/java/com/tc/l2/msg/PlatformInfoRequest.java
This PR will need to be updated to the next API release prior to merge.
For now, it is provided for review/discussion.
> (READY) Implementation of IStripeMonitoring support

- dso-l2/src/main/java/com/tc/l2/state/DummyStateManager.java
- dso-l2/src/main/java/com/tc/l2/state/ElectionContext.java
- dso-l2/src/main/java/com/tc/l2/state/ElectionManager.java
- dso-l2/src/main/java/com/tc/l2/state/ElectionManagerImpl.java
- dso-l2/src/main/java/com/tc/l2/state/StateManager.java
- dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/l2/state/StateManagerImplTest.java
- dso-l2/src/test/java/com/tc/net/groups/TCGroupManagerImplTest.java
- dso-l2/src/test/java/com/tc/net/groups/TCGroupMessageWrapperTest.java
- dso-l2/src/test/java/com/tc/net/groups/TestStateManager.java
- dso-l2/src/test/java/com/tc/net/groups/VirtualTCGroupStateManagerTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
- tc-messaging/src/main/java/com/tc/l2/msg/L2StateMessage.java
- tc-messaging/src/test/java/com/tc/l2/msg/L2StateMessageTest.java
Opening this PR for discussion
> [TAB-6899] StateManager - handle network partitions

- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/impl/ServerBuilder.java
- dso-l2/src/main/java/com/tc/objectserver/impl/StandardServerBuilder.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageProviderConfiguration.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageServiceProvider.java
- dso-l2/src/test/java/com/tc/objectserver/persistence/FlatFileStorageServiceProviderTest.java
These were sort of in the way of, or otherwise noticed during, largely-unrelated prototyping work.
> Small fixes

- pom.xml
> upgrading to plugin 1.2.20 which works without svn

- .gitignore
- client-runtime/pom.xml
- terracotta-kit/pom.xml
- terracotta-kit/src/assemble/distribution.xml
* Create lib folder for client-* artifacts
* Create logging folder for slf4j-api and logging/impl for default log4j
binding
> Rework client side of kit

- dso-l2/src/main/java/com/tc/l2/handler/PlatformInfoRequestHandler.java
- dso-l2/src/main/java/com/tc/objectserver/entity/AbstractServerEntityRequestResponse.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/MessagePayload.java
- dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
- dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityRequestResponse.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
- dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
- dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/RequestProcessorTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ServerEntityRequestImplTest.java
- pom.xml
- tc-messaging/src/main/java/com/tc/l2/msg/PlatformInfoRequest.java
Fix Java6/8
Add execution strategy
Add reconfigure APIs
> [DO NOT MERGE] Entity API changes

- dso-l2/src/main/java/com/tc/services/LocalMonitoringProducer.java
NPE caused by split brain scenario fixed by null check
NPE caused by null parent path fixed by null check
> Fix monitor reporting

- dso-l2/src/main/java/com/tc/management/beans/TCServerInfo.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileKeyValueStorage.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFilePersistentStorage.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileProperties.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageProviderConfiguration.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageProviderConfigurationParser.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageServiceProvider.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileWrite.java
- dso-l2/src/main/java/com/tc/server/TCServer.java
- dso-l2/src/main/java/com/tc/server/TCServerImpl.java
- dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistryImpl.java
- dso-l2/src/main/resources/META-INF/services/org.terracotta.config.service.ServiceConfigParser
- dso-l2/src/main/resources/META-INF/services/org.terracotta.entity.ServiceProvider
- dso-l2/src/main/resources/restartable-platform-persistence.xsd
- dso-l2/src/test/java/com/tc/objectserver/persistence/FlatFileStorageServiceProviderTest.java
- dso-l2/src/test/java/com/tc/server/NullTCServerInfo.java
- management/src/main/java/com/tc/management/beans/TCServerInfoMBean.java
Specific changes carved out, prior to the forthcoming configuration change.
As discussed, I will self-merge.
> Pre config

- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/impl/StandardServerBuilder.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/ClientStatePersistor.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/ClusterStatePersistor.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/EmulatedPersistentStorage.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/EmulatedStorageServiceProvider.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/EntityPersistor.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlushingWrite.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformPersistentStorage.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformStorageServiceProvider.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/PersistentStorageProperties.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/Persistor.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/SynchronizedKeyValueStorage.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/TestClusterStatePersistor.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/TransactionOrderPersistor.java
- dso-l2/src/main/resources/META-INF/services/org.terracotta.config.service.ServiceConfigParser
- dso-l2/src/main/resources/META-INF/services/org.terracotta.entity.ServiceProvider
- dso-l2/src/test/java/com/tc/l2/state/StateManagerTest.java
- dso-l2/src/test/java/com/tc/objectserver/persistence/EntityPersistorTest.java
- dso-l2/src/test/java/com/tc/objectserver/persistence/TransactionOrderPersistorTest.java
- pom.xml
-updates the deps
-includes support for IPlatformPersistence
-includes emulator for IPersistentStorage
-also changes the internal consumers of IPersistentStorage to IPlatformPersistence
Will self-merge, as discussed
> Support for IPlatformPersistence

- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/services/EntityMessengerProvider.java
- dso-l2/src/main/java/com/tc/services/EntityMessengerService.java
- dso-l2/src/main/java/com/tc/services/SingleThreadedTimer.java
- dso-l2/src/test/java/com/tc/services/EntityMessengerProviderTest.java
- dso-l2/src/test/java/com/tc/services/SingleThreadedTimerTest.java
- pom.xml
This needs to be updated to the correct release version, prior to merge, once the upstream release is available.
> (READY) IEntityMessenger timer support

- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/EmulatedStorageServiceProvider.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/FlatFileStorageServiceProvider.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/NullPlatformStorageServiceProvider.java
- dso-l2/src/main/java/com/tc/services/PlatformConfigurationImpl.java
- dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistryImpl.java
- dso-l2/src/test/java/com/tc/server/TestServiceProvider.java
- management/src/test/resources/security-conf1-defaults.xml
- management/src/test/resources/security-conf2.xml
- management/src/test/resources/storage-xsd-test.xml
- pom.xml
DO NOT MERGE -- must be versioned
Add support for configuration objects
> [DO NOT MERGE] Fix terracotta-configuration#26 - Add support for configuration objects

- connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java
- dso-l1/src/main/java/com/tc/object/ExceptionUtils.java
- pom.xml
Can only merge after API and config are released.
> Support EntityAPI exceptions

- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
-GroupManager should be GroupManager<AbstractGroupMessage>
-removed unused method
-remove constant return value
> Fix warnings

- dso-l2/src/main/java/com/tc/config/schema/setup/BaseConfigurationSetupManagerFactory.java
- dso-l2/src/main/java/com/tc/config/schema/setup/ConfigurationSetupManagerFactory.java
- dso-l2/src/main/java/com/tc/config/schema/setup/L2ConfigurationSetupManagerImpl.java
- dso-l2/src/main/java/com/tc/object/config/schema/L2Config.java
- dso-l2/src/main/java/com/tc/object/config/schema/L2ConfigObject.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
Will write some unit tests around this when it is coalesced in a later change.
> Fix warnings and handle an exception TODO

- galvan-support/src/main/java/org/terracotta/testing/master/BasicHarnessEntry.java
- galvan-support/src/main/java/org/terracotta/testing/rules/BasicExternalCluster.java
- galvan-support/src/test/java/org/terracotta/testing/rules/SimpleActivePassiveWithClassRuleIT.java
- galvan-support/src/test/java/org/terracotta/testing/support/MultiProcessGalvanTest.java
- pom.xml
Note that this requires coordination through release before it can be merged.
> Update to handle removal of isRestartable() from Galvan

- dso-l2/src/main/java/com/tc/objectserver/api/EntityManager.java
- dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
- dso-l2/src/main/java/com/tc/objectserver/api/ServerEntityAction.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/MessagePayload.java
- dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
- dso-l2/src/main/java/com/tc/objectserver/handler/EntityExistenceHelpers.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
- dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/RequestProcessorTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
- tc-messaging/src/main/java/com/tc/l2/msg/SyncReplicationActivity.java
This isn't yet ready for merge as it seems to have introduced some intermittent test failures, downstream.
> (READY) Sync entities in the same order they were created

- dso-l2/src/main/java/com/tc/services/DelegatingServiceRegistry.java
-this is a configuration/installation, not an internal bug, so it should be something more descriptive than an assertion failure
> Throw IllegalArgumentException on duplicate service match

- dso-l2/src/main/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollector.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/objectserver/core/impl/ManagementTopologyEventCollectorTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
Fixed some unit test issues, reverted a recent change which was causing some problems, and implemented #461.
> Issue 461 and various fixes

- dso-l2/src/main/java/com/tc/objectserver/core/api/ServerConfigurationContext.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
- dso-l2/src/main/java/com/tc/objectserver/handler/GroupMessageBatchContext.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
- tc-messaging/src/main/java/com/tc/l2/msg/IBatchableGroupMessage.java
- tc-messaging/src/main/java/com/tc/l2/msg/ReplicationAckTuple.java
- tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java
- tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessageAck.java
This also adds a new thread (stage) for the passive->active serialization/send path (this was formerly being done on whatever thread called into it at the time).
> Issue 423: Generalize group channel batching

- dso-l2/src/main/java/com/tc/objectserver/api/ManagementKeyCallback.java
- dso-l2/src/main/java/com/tc/objectserver/api/ServerEntityAction.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/LocalPipelineFlushMessage.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityRequestImpl.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
- dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/objectserver/entity/EntityManagerImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
- tc-messaging/src/main/java/com/tc/entity/VoltronEntityMessage.java
- tc-messaging/src/main/java/com/tc/l2/msg/SyncReplicationActivity.java
Be more aggressive about GC of removable ManagedEntities
> Fix #468 - Check for ManagedEntity removal on every flush

- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
- dso-l1/src/main/java/com/tc/object/EntityClientEndpointImpl.java
- dso-l1/src/main/java/com/tc/object/InFlightMessage.java
- dso-l1/src/main/java/com/tc/object/request/RequestReceiveHandler.java
- dso-l1/src/main/java/com/tc/object/request/RequestResponseHandler.java
- dso-l2/src/main/java/com/tc/objectserver/entity/AbstractServerEntityRequestResponse.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ServerEntityRequestImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
- pom.xml
- tc-messaging/src/main/java/com/tc/entity/DiagnosticResponseImpl.java
- tc-messaging/src/main/java/com/tc/entity/VoltronEntityAppliedResponseImpl.java
- tc-messaging/src/main/java/com/tc/entity/VoltronEntityMessage.java
- tc-messaging/src/main/java/com/tc/net/protocol/tcm/TCMessageType.java
-terracotta-apis 1.2.0-pre14
-terracotta-configuration 10.2.0-pre14
Changed uses of "APPLIED" to "COMPLETED" to sync up with terms used in the API an documentation.
> Update deps and naming

- common/src/main/java/com/tc/async/impl/StageQueueImpl.java
- common/src/test/java/com/tc/async/impl/StageQueueImplTest.java
> Fix #484 - fcheck rollover not accounted for.  Use abs value

- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
> Retry l1 port bind

- common/src/main/java/com/tc/net/protocol/transport/ClientConnectionEstablisher.java
- common/src/main/java/com/tc/net/protocol/transport/ConnectionPolicyImpl.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportBase.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportState.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportStatus.java
- common/src/main/java/com/tc/net/protocol/transport/ServerMessageTransport.java
- common/src/test/java/com/tc/net/protocol/transport/ConnectionPolicyTest.java
- common/src/test/java/com/tc/net/protocol/transport/ServerMessageTransportTest.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
For Discussion.  Working on some tests currently.
> Fix reconnects and failovers

- connection-impl/src/main/java/com/terracotta/connection/EntityClientServiceFactory.java
- connection-impl/src/main/java/com/terracotta/connection/TerracottaConnection.java
- connection-impl/src/main/java/com/terracotta/connection/entity/TerracottaEntityRef.java
- connection-impl/src/test/java/com/terracotta/connection/entity/TerracottaEntityRefTest.java
- connection-loader/src/main/java/com/terracotta/diagnostic/DiagnosticEntityClientService.java
- pom.xml
Depends on terracotta-apis and terracotta-config being released after this change:  https://github.com/Terracotta-OSS/terracotta-apis/pull/211
> Updated to account for changes to the API fetchEntity()

- dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java
- dso-l2/src/test/java/com/tc/l2/state/StateManagerImplTest.java
fix a bug where non-new passive joining does not zap when it should
> Change zap logic

- common/src/main/java/com/tc/net/protocol/transport/ServerStackProvider.java
- common/src/main/java/com/tc/util/io/FileUtils.java
- common/src/main/java/com/tc/util/io/IOUtils.java
- dso-l2/src/main/java/com/tc/config/schema/setup/StandardXMLFileConfigurationCreator.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/impl/PluggableSecurityManager.java
- dso-l2/src/main/java/com/tc/objectserver/impl/ServerBuilder.java
- dso-l2/src/main/java/com/tc/objectserver/impl/StandardServerBuilder.java
- dso-l2/src/main/java/com/tc/server/TCServerImpl.java
- galvan-support/src/main/java/org/terracotta/testing/rules/BasicExternalCluster.java
- pom.xml
Add ability to ignore server crashes.
Add ability to plug-in a buffermanagerfactory
Cleanup dependencies
> Roll to new versions

- common/src/main/java/com/tc/net/core/TCConnectionImpl.java
- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- common/src/test/java/com/tc/net/core/DetachedTest.java
- common/src/test/java/com/tc/net/core/TCConnectionImplTest.java
- common/src/test/java/com/tc/net/protocol/tcm/MessageChannelTest.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
must be rebased after previous merge
> Fix #552 - Fix BufferManager failure handling

- common/src/main/java/com/tc/async/impl/MultiStageQueueImpl.java
Stupid reference left in, took it out.
> Issue 350 leftovers: remove unneeded refs to updateable heap

- dso-l2/src/main/java/com/tc/objectserver/entity/InvokeContextImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/testentity/TestEntityServer.java
- pom.xml
> Message tracking

- dso-l2/src/main/java/com/tc/config/schema/CommonL2Config.java
- dso-l2/src/main/java/com/tc/config/schema/CommonL2ConfigObject.java
- dso-l2/src/main/java/com/tc/object/config/schema/L2Config.java
- dso-l2/src/main/java/com/tc/object/config/schema/L2ConfigObject.java
> Cleanup management port code

- common/src/main/java/com/tc/object/net/DSOChannelManager.java
- common/src/main/java/com/tc/object/net/DSOChannelManagerImpl.java
- common/src/main/java/com/tc/object/net/MockChannelManager.java
- dso-l1/src/main/java/com/tc/object/ClientShutdownManager.java
- dso-l1/src/main/java/com/tc/object/handshakemanager/ClientHandshakeManager.java
- dso-l1/src/main/java/com/tc/object/handshakemanager/ClientHandshakeManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
- dso-l2/src/main/java/com/tc/objectserver/handler/GroupMessageBatchContext.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSender.java
- dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
- dso-l2/src/main/java/com/tc/objectserver/impl/ConnectionIDFactoryImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/Persistor.java
- dso-l2/src/main/java/com/tc/services/BestEffortsMonitoring.java
- dso-l2/src/main/java/com/tc/services/LocalMonitoringProducer.java
- dso-l2/src/main/java/com/tc/services/PlatformConfigurationImpl.java
- dso-l2/src/main/java/com/tc/services/PlatformServiceImpl.java
- dso-l2/src/main/java/com/tc/services/PlatformServiceProvider.java
- dso-l2/src/test/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManagerTest.java
- dso-l2/src/test/java/com/tc/objectserver/impl/ConnectionIDFactoryImplTest.java
- dso-l2/src/test/java/com/tc/stats/MBeanRegTest.java
- tc-messaging/src/main/java/com/tc/net/protocol/transport/ConnectionID.java
- tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeAckMessage.java
- tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeAckMessageImpl.java
- tc-messaging/src/main/java/com/tc/util/ProductCapabilities.java
- tc-messaging/src/main/java/com/tc/util/ProductID.java
add a permanent product type
add product negotiation with client
remove persistence from handshake
unlock waiters on server disconnect
> Add perm product

- dso-l2/src/main/java/com/tc/objectserver/impl/ConnectionIDFactoryImpl.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/ClientStatePersistor.java
- dso-l2/src/test/java/com/tc/objectserver/impl/ConnectionIDFactoryImplTest.java
product type can't change on channel removal
> Fix connection tracking by product type

- common/src/main/java/com/tc/net/core/CoreNIOServices.java
- common/src/main/java/com/tc/net/protocol/transport/ConnectionPolicyImpl.java
- common/src/main/java/com/tc/net/protocol/transport/ServerStackProvider.java
- dso-l2/src/main/java/com/tc/l2/L2DebugLogging.java
- dso-l2/src/main/java/com/tc/l2/ha/StripeIDStateManagerImpl.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
- dso-l2/src/main/java/com/tc/objectserver/impl/StandardServerBuilder.java
This PR removes some unnecessary logging at info level and rewording some logs.
> cleanup info logs

- galvan-support/src/main/java/org/terracotta/testing/rules/BasicExternalCluster.java
- galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterActivePassiveIT.java
- pom.xml
> Add support for configuring reconnect window in BasicExternalCluster

- build-parent/pom.xml
- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- common/src/main/java/com/tc/net/protocol/transport/ServerMessageTransport.java
- common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java
- common/src/test/java/com/tc/net/protocol/tcm/MessageChannelTest.java
- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
- terracotta-kit/src/assemble/server/bin/start-tc-server.bat
- terracotta-kit/src/assemble/server/bin/start-tc-server.sh
> Small cleanup

- terracotta-kit/src/assemble/server/bin/start-tc-server.sh
Made bash syntax consistent and corrected what appeared to be bugs - classpath quoting and generation.
> syntax and logical corrections

- galvan-support/src/main/java/org/terracotta/testing/master/BasicHarnessEntry.java
- galvan-support/src/main/java/org/terracotta/testing/rules/BasicExternalCluster.java
- galvan-support/src/main/java/org/terracotta/testing/rules/BasicExternalClusterBuilder.java
- galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterActivePassiveIT.java
- galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterBadPathIT.java
- galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterClassRuleIT.java
- galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterImmediateControlIT.java
- galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterMethodRuleIT.java
- galvan-support/src/test/java/org/terracotta/testing/rules/CorruptConfigWithClassRuleIT.java
- galvan-support/src/test/java/org/terracotta/testing/rules/InvalidPathTestIT.java
- galvan-support/src/test/java/org/terracotta/testing/rules/SimpleActivePassiveWithClassRuleIT.java
- galvan-support/src/test/java/org/terracotta/testing/support/SimpleClientStartUpIT.java
- pom.xml
This PR adapt to changes made in Terracotta-OSS/galvan#168
> galvan-support: Add support for overriding tc properties

- common/src/main/java/com/tc/tracing/Trace.java
slight optimization to only trace items when asked for.
> Only trace when asked for

- common/src/main/java/com/tc/async/api/Sink.java
- common/src/main/java/com/tc/async/impl/AbstractStageQueueImpl.java
- common/src/main/java/com/tc/async/impl/MockSink.java
- common/src/main/java/com/tc/async/impl/MultiStageQueueImpl.java
- common/src/main/java/com/tc/async/impl/NullSink.java
- common/src/main/java/com/tc/async/impl/OrderedSink.java
- common/src/main/java/com/tc/async/impl/SingletonStageQueueImpl.java
- common/src/main/java/com/tc/async/impl/StageImpl.java
- common/src/main/java/com/tc/async/impl/StageQueue.java
- common/src/main/java/com/tc/net/core/TCConnectionImpl.java
- common/src/main/java/com/tc/net/protocol/transport/ClientConnectionEstablisher.java
- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- common/src/main/java/com/tc/objectserver/api/TestSink.java
- common/src/main/java/com/tc/util/concurrent/TCFuture.java
- common/src/test/java/com/tc/async/impl/MultiStageQueueImplTest.java
- connection-loader/src/main/java/com/terracotta/connection/TerracottaInternalClientImpl.java
- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
- dso-l1/src/main/java/com/tc/object/config/ConnectionInfoConfig.java
- dso-l1/src/main/java/com/tc/object/handler/ClusterInternalEventsHandler.java
- dso-l1/src/main/java/com/tc/object/handshakemanager/ClientHandshakeManagerImpl.java
- dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
- dso-l2/src/main/java/com/tc/l2/ha/ClusterStateImpl.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicatedTransactionHandlerTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ReplicationSenderTest.java
- tc-messaging/src/main/java/com/tc/entity/VoltronEntityAppliedResponseImpl.java
- tc-messaging/src/main/java/com/tc/net/protocol/tcm/TCMessageImpl.java
Make the ClientEntityManager shutdown more friendly to consumers
Remove thread interrupts from Stage destroy
cleanup comm stack logging
currently adding tests so do not merge
> Stage shutdown

- common/src/main/java/com/tc/async/impl/MultiStageQueueImpl.java
- common/src/test/java/com/tc/async/impl/MultiStageQueueImplTest.java
The partition strategy in shortest queue uses a "hand", and ever
increasing AtomicInteger. Like a fool, I failed to check for
overflow, leading to failures when it rolls over.
Moved relevant code into nextPartition() and did some sanity
chacking and response on value.
> Fix for integer overflow in shortestQueue code

- common/src/main/java/com/tc/util/ManagedServiceLoader.java
- dso-l2/src/main/java/com/tc/objectserver/api/ManagedEntity.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/PlatformEntity.java
- dso-l2/src/main/java/com/tc/services/EntityMessengerProvider.java
- dso-l2/src/main/java/com/tc/services/EntityMessengerService.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
- dso-l2/src/test/java/com/tc/services/EntityMessengerServiceTest.java
- galvan-support/src/main/java/org/terracotta/testing/master/BasicHarnessEntry.java
- pom.xml
add OverrideServiceType support as well.
> Refactor EntityMessengerService to be more useful

- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/MessagePayload.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
MessageCodec errors are not handled properly.
> Process codec errors properly from server to client

- common/src/main/java/com/tc/async/impl/DirectSink.java
- common/src/main/java/com/tc/async/impl/SingletonStageQueueImpl.java
- dso-l2/src/main/java/com/tc/objectserver/api/ServerEntityAction.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/NoopResultCapture.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ManagedEntityImplTest.java
Debugging and safety in DirectSink
Single queue code cleanup
Really flush when flush is called for in ManagedEntityImpl
Import cleanup
> Code cleanup and debugging changes

- dso-l1/src/main/java/com/tc/object/ClientBuilder.java
- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
- dso-l1/src/main/java/com/tc/object/StandardClientBuilder.java
- dso-l1/src/main/java/com/tc/object/handshakemanager/ClientHandshakeManagerImpl.java
- dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
- dso-l1/src/test/java/com/tc/object/DistributedObjectClientTest.java
- dso-l2/src/main/java/com/tc/objectserver/api/ServerEntityAction.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicatedTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
> connection fixes

- common/src/main/java/com/tc/net/core/TCConnectionImpl.java
- common/src/main/java/com/tc/net/core/TCConnectionManagerImpl.java
- common/src/main/java/com/tc/util/ManagedServiceLoader.java
- dso-l2/src/main/java/com/tc/classloader/ServiceLocator.java
- dso-l2/src/main/java/com/tc/objectserver/entity/MessagePayload.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ChannelLifeCycleHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ChannelLifeCycleHandlerTest.java
- tc-messaging/src/main/java/com/tc/entity/VoltronEntityAppliedResponseImpl.java
- tc-messaging/src/main/java/com/tc/util/ProductID.java
> Misc fixes and optimization

- common/src/main/java/com/tc/runtime/TCMemoryManagerImpl.java
- common/src/main/java/com/tc/runtime/TCMemoryManagerJdk15PoolMonitor.java
- terracotta-kit/src/assemble/server/bin/start-tc-server.bat
- terracotta-kit/src/assemble/server/bin/start-tc-server.sh
Also update the max direct memory value used on command line, IBM VM no
longer parses 2^63-1 properly
> [master] Issue #794 Degrade when memory pools not identified

- dso-l1/src/main/java/com/tc/object/config/ConnectionInfoConfig.java
- tc-messaging/src/main/java/com/tc/net/TCSocketAddress.java
More changes in terracotta-platform and terracotta-enterprise.
> TDB-2589: IPv6 changes

- common/src/main/java/com/tc/net/core/AbstractBufferManager.java
- common/src/main/java/com/tc/net/core/ClearTextBufferManager.java
This PR adds `AbstractBufferManager` which contains  common code that can be shared by other `BufferManager` implementations. Please review
> Fix #791: Refactor ClearTextBufferManager

- terracotta-kit/src/assemble/server/bin/start-tc-server.sh
Corrections to previous approach in #758 due to changes to installer
> Setting JAVA_HOME via installer setenv if available

- common/src/main/java/com/tc/voter/VoterManager.java
- dso-l2/src/main/java/com/tc/l2/state/ServerVoterManager.java
- pom.xml
- voter/pom.xml
- voter/src/main/java/org/terracotta/voter/ClientVoterManager.java
This PR defines the `VoterManager` and its client and server counterpart SPIs. The `ServerVoterManager` is the integration point for the server to interact with the voting system. `ClientVoterManager` defines the client-server interaction of a voter.
> Voter manager SPI

- common/src/main/java/com/tc/tracing/Trace.java
- dso-l1/src/main/java/com/tc/object/InFlightMessage.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/EntityManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/NoopResultCapture.java
- dso-l2/src/main/java/com/tc/objectserver/entity/PassiveResultCapture.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ResultCaptureImpl.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/RetirementManager.java
- dso-l2/src/main/java/com/tc/objectserver/handler/VoltronMessageHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/services/TerracottaServiceProviderRegistryImpl.java
update the zapped list when a server goes away
Only try and send result messages to real clients
> Trivial fixes

- dso-l2/src/main/java/com/tc/l2/state/ConsistencyManagerImpl.java
no test because no time.  Will add.
> Only use server votes on start

- common/src/main/java/com/tc/net/protocol/ClientNetworkStackHarness.java
- common/src/main/java/com/tc/net/protocol/tcm/ClientMessageChannel.java
- common/src/main/java/com/tc/net/protocol/tcm/ClientMessageChannelImpl.java
- common/src/main/java/com/tc/net/protocol/transport/ClientConnectionErrorDetails.java
- common/src/main/java/com/tc/net/protocol/transport/ClientConnectionErrorListener.java
- common/src/main/java/com/tc/net/protocol/transport/ClientConnectionEstablisher.java
- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- common/src/main/java/com/tc/util/concurrent/TCFuture.java
- common/src/test/java/com/tc/net/protocol/transport/ClientConnectionErrorDetailsTest.java
- common/src/test/java/com/tc/net/protocol/transport/ClientConnectionEstablisherTest.java
- common/src/test/java/com/tc/util/concurrent/TCFutureTest.java
- connection-loader/src/main/java/com/terracotta/connection/TerracottaInternalClient.java
- connection-loader/src/main/java/com/terracotta/connection/TerracottaInternalClientImpl.java
- connection-loader/src/main/java/com/terracotta/connection/api/AbstractConnectionService.java
- connection-loader/src/main/java/com/terracotta/connection/api/DetailedConnectionException.java
- connection-loader/src/test/java/com/terracotta/connection/api/DetailedConnectionExceptionTest.java
- dso-l1/src/main/java/com/tc/object/ClientBuilder.java
- dso-l1/src/main/java/com/tc/object/StandardClientBuilder.java
Creating pull request for enhanced approach for issue 805. Also fixed an issue in TCFuture class.
> Issue 805 : Improved exception handling when connection between client and server fails.

- common/src/main/java/com/tc/async/impl/MultiStageQueueImpl.java
- common/src/main/java/com/tc/async/impl/SingletonStageQueueImpl.java
- common/src/main/java/com/tc/async/impl/StageImpl.java
- common/src/main/java/com/tc/async/impl/StageQueue.java
- common/src/main/java/com/tc/net/protocol/tcm/AbstractMessageChannel.java
- common/src/test/java/com/tc/async/impl/MultiStageQueueImplTest.java
- common/src/test/java/com/tc/async/impl/StageImplTest.java
- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
- dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/ConnectionIDFactoryImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/ClientStatePersistor.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/Persistor.java
- dso-l2/src/test/java/com/tc/l2/state/StateManagerImplTest.java
- dso-l2/src/test/java/com/tc/net/protocol/transport/ServerStackProviderTest.java
- dso-l2/src/test/java/com/tc/objectserver/impl/ConnectionIDFactoryImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/persistence/PersistorTest.java
See commit messages.  Tests updated.
> Multiple Bug Fixes

- common/src/main/java/com/tc/net/core/BufferManagerFactory.java
- common/src/main/java/com/tc/net/core/CoreNIOServices.java
- common/src/main/java/com/tc/net/core/TCConnectionImpl.java
- common/src/test/java/com/tc/net/core/TCConnectionImplTest.java
- common/src/test/java/com/tc/net/protocol/transport/TCConnectionTransportTest.java
close needs a better interaction with BufferManager
> Stop on close

- common/src/main/java/com/tc/net/protocol/transport/ClientConnectionEstablisher.java
- common/src/test/java/com/tc/net/protocol/transport/ClientConnectionEstablisherTest.java
- dso-l2/src/main/java/com/tc/l2/ha/BlockTimeWeightGenerator.java
- dso-l2/src/main/java/com/tc/l2/ha/ChannelWeightGenerator.java
- dso-l2/src/main/java/com/tc/l2/ha/ConsistencyManagerWeightGenerator.java
- dso-l2/src/main/java/com/tc/l2/state/ConsistencyManagerImpl.java
- dso-l2/src/main/java/com/tc/l2/state/ServerVoterManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/l2/ha/BlockTimeWeightGeneratorTest.java
- dso-l2/src/test/java/com/tc/l2/ha/ConsistencyManagerWeightGeneratorTest.java
Remove transaction counter weighting
Add consistency manager weighting
Add block time weighting
fix no active exception handling
> Fix election weighting

- common/src/main/java/com/tc/net/protocol/tcm/ClientMessageChannelImpl.java
- dso-l2/src/main/java/com/tc/l2/state/ConsistencyManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- tc-messaging/src/main/java/com/tc/util/ProductID.java
Fixes internal client attach to consistent cluster
> Fix product attach [master]

- common/src/main/java/com/tc/net/protocol/tcm/ClientMessageChannelImpl.java
- dso-l2/src/main/java/com/tc/l2/state/ConsistencyManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- tc-messaging/src/main/java/com/tc/util/ProductID.java
fix product attach for internal clients on consistent clusters
> Fix product attach [5.4]

- common/src/main/java/com/tc/net/core/CoreNIOServices.java
- common/src/main/java/com/tc/net/core/TCConnectionImpl.java
- common/src/main/java/com/tc/net/protocol/ServerNetworkStackHarness.java
- common/src/main/java/com/tc/net/protocol/delivery/OOOConnectionWatcher.java
- common/src/main/java/com/tc/net/protocol/tcm/ChannelManagerImpl.java
- common/src/main/java/com/tc/net/protocol/tcm/ClientMessageChannelImpl.java
- common/src/main/java/com/tc/net/protocol/tcm/ServerMessageChannelImpl.java
- common/src/main/java/com/tc/net/protocol/transport/AbstractMessageTransport.java
- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportBase.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportState.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportStatus.java
- common/src/main/java/com/tc/net/protocol/transport/ServerMessageTransport.java
- common/src/main/java/com/tc/net/protocol/transport/ServerStackProvider.java
- common/src/main/java/com/tc/object/net/DSOChannelManagerImpl.java
- common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java
- common/src/test/java/com/tc/net/protocol/tcm/MessageChannelTest.java
- common/src/test/java/com/tc/net/protocol/transport/ServerMessageTransportTest.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/core/api/Guardian.java
- dso-l2/src/main/java/com/tc/objectserver/core/impl/ServerManagementContext.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/server/TCServerImpl.java
- dso-l2/src/test/java/com/tc/net/groups/MockStageManagerFactory.java
- dso-l2/src/test/java/com/tc/net/groups/TCGroupManagerNodeJoinedTest.java
- dso-l2/src/test/java/com/tc/net/protocol/transport/ServerStackProviderTest.java
- tc-messaging/src/main/java/com/tc/net/core/TCConnection.java
> Consolidated Fix Merge

- common/src/main/java/com/tc/net/core/TCConnectionImpl.java
- common/src/main/java/com/tc/net/protocol/delivery/OnceAndOnlyOnceProtocolNetworkLayerImpl.java
- common/src/main/java/com/tc/net/protocol/tcm/ServerMessageChannel.java
- common/src/main/java/com/tc/net/protocol/tcm/ServerMessageChannelImpl.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransport.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportBase.java
- common/src/main/java/com/tc/net/protocol/transport/ServerMessageTransport.java
- dso-l2/src/main/java/com/tc/objectserver/core/api/GuardianContext.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DiagnosticsHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/server/TCServerImpl.java
add more information to guardian context property map
fix double close on ServerMessageTransport
> Guardian context

- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportBase.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportStatus.java
- dso-l2/src/main/java/com/tc/objectserver/core/api/GuardianContext.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
> Fix guardian object properties reporting

- dso-l1/src/main/java/com/tc/object/handshakemanager/ClientHandshakeManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityFactory.java
- pom.xml
also add PermanentEntity typing
> Bump Parent Version

- dso-l2/src/main/java/com/tc/config/schema/setup/StandardConfigurationSetupManagerFactory.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- galvan-support/src/main/java/org/terracotta/testing/rules/BasicExternalCluster.java
- pom.xml
with an added option for unsafe startups. Dependent on https://github.com/Terracotta-OSS/galvan/pull/192
> Safe start servers by default in availability mode 

- dso-l2/src/main/java/com/tc/config/schema/setup/L2ConfigurationSetupManager.java
- dso-l2/src/main/java/com/tc/config/schema/setup/L2ConfigurationSetupManagerImpl.java
- dso-l2/src/main/java/com/tc/config/schema/setup/StandardConfigurationSetupManagerFactory.java
- dso-l2/src/main/java/com/tc/l2/state/SafeStartupManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- galvan-support/src/main/java/org/terracotta/testing/rules/BasicExternalCluster.java
- galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterFOPAvailabilityIT.java
- pom.xml
with consistent startup option
> Remove unsafe startup option and replace safe startup

- common/src/main/java/com/tc/net/basic/BasicConnection.java
- common/src/main/java/com/tc/properties/TCPropertiesConsts.java
- common/src/main/resources/com/tc/properties/tc.properties
- common/src/test/java/com/tc/util/TCPropertiesConstsTest.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
- dso-l2/src/test/resources/com/tc/properties/tests.properties
Underflow can occur with large messages
> make sure all bytes of a message are pushed to the network

- dso-l2/src/main/java/com/tc/server/TCServerMain.java
This fix allows to use OverrideService annotation to override other providers.
> Fix ConfigurationProvider lookup

- common/src/main/java/com/tc/object/StatType.java
- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/main/java/com/tc/object/EntityClientEndpointImpl.java
- dso-l1/src/main/java/com/tc/object/InFlightMessage.java
- dso-l1/src/main/java/com/tc/object/InFlightStats.java
- dso-l1/src/main/java/com/tc/object/request/MultiRequestReceiveHandler.java
- dso-l1/src/main/java/com/tc/object/request/RequestResponseHandler.java
- dso-l1/src/main/java/com/terracotta/diagnostic/DiagnosticClientEntityManager.java
- dso-l2/src/main/java/com/tc/config/DefaultConfigurationProvider.java
- dso-l2/src/main/java/com/tc/config/ServerConfigurationManager.java
- dso-l2/src/main/java/com/tc/objectserver/api/StatisticsCapture.java
- dso-l2/src/main/java/com/tc/objectserver/entity/AbstractServerEntityRequestResponse.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ServerEntityRequestResponse.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/server/CommandLineParser.java
- dso-l2/src/test/java/com/tc/config/DefaultConfigurationProviderTest.java
- dso-l2/src/test/java/com/tc/config/GroupConfigurationTest.java
- dso-l2/src/test/java/com/tc/config/ServerConfigurationManagerTest.java
- dso-l2/src/test/java/com/tc/config/ServerConfigurationTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ServerEntityRequestImplTest.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
- dso-l2/src/test/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManagerTest.java
- dso-l2/src/test/java/com/tc/server/CommandLineParserTest.java
- tc-messaging/src/main/java/com/tc/entity/LinearVoltronEntityMultiResponse.java
- tc-messaging/src/main/java/com/tc/entity/ReplayVoltronEntityMultiResponse.java
- tc-messaging/src/main/java/com/tc/entity/VoltronEntityMultiResponse.java
add server statistics transferred to clients
fix diagnostic information about extended configs
fix license headers
> Fix message contention

- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
- dso-l1/src/main/java/com/tc/object/request/MultiRequestReceiveHandler.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/core/api/ServerConfigurationContext.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActivePassiveAckWaiter.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ReplicationSender.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationReceivingAction.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ReplicationSendingAction.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ActiveToPassiveReplicationTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ReplicationSenderTest.java
- tc-messaging/src/main/java/com/tc/entity/LinearVoltronEntityMultiResponse.java
- tc-messaging/src/main/java/com/tc/entity/VoltronEntityMultiResponse.java
some important replication speed-up changes particularly for multi-passive setups.  The most critical is 5a1b188.
> Replication perf

- common/src/main/java/com/tc/async/impl/StageController.java
- common/src/main/java/com/tc/async/impl/StageImpl.java
- common/src/main/java/com/tc/async/impl/StageManagerImpl.java
- common/src/main/java/com/tc/net/core/CoreNIOServices.java
- common/src/main/java/com/tc/net/core/TCConnectionImpl.java
- common/src/test/java/com/tc/async/impl/StageControllerTest.java
- dso-l2/src/main/java/com/tc/l2/handler/L2StateChangeHandler.java
- dso-l2/src/main/java/com/tc/management/beans/TCServerInfo.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/MessagePayload.java
- dso-l2/src/main/java/com/tc/objectserver/entity/NoReplicationBroker.java
- dso-l2/src/main/java/com/tc/objectserver/entity/PassiveReplicationBroker.java
- dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/server/TCServerImpl.java
re-arranged startup to remove requirement for placeholder passive entities
refined logging
fixed listener close to close write-side before read
> Combined fixes

- common/src/main/java/com/tc/net/basic/BasicConnection.java
- common/src/main/java/com/tc/properties/TCPropertiesConsts.java
- dso-l2/src/main/java/com/tc/objectserver/core/impl/ServerManagementContext.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ReplicationSender.java
- dso-l2/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
- dso-l2/src/main/java/com/tc/objectserver/entity/SyncRequestProcessorHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handler/GroupMessageBatchContext.java
- dso-l2/src/main/java/com/tc/objectserver/handler/RetirementManager.java
- dso-l2/src/main/java/com/tc/objectserver/handler/VoltronMessageHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/stats/DSO.java
- dso-l2/src/main/java/com/tc/stats/api/DSOMBean.java
- tc-messaging/src/main/java/com/tc/l2/msg/IBatchableGroupMessage.java
- tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessage.java
- tc-messaging/src/main/java/com/tc/l2/msg/ReplicationMessageAck.java
- tc-messaging/src/main/java/com/tc/l2/msg/SyncReplicationActivity.java
add control and visibility to the message handler through DSO MBean
> mbean additions

- dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java
- pom.xml
> Bump galvan version

- common/src/main/java/com/tc/net/basic/BasicConnection.java
- common/src/main/java/com/tc/net/protocol/tcm/ClientMessageChannelImpl.java
- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java
- dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java
- pom.xml
* make client connection closure more resilient to IOExceptions during close.  Make sure reader thread is shut regardless of socket errors.
* Make StateManager more resilient to slow machines and multiple election won messages
* Revert galvan version
> Resiliency

- common/src/main/java/com/tc/net/basic/BasicConnection.java
- common/src/main/java/com/tc/net/core/CoreNIOServices.java
- dso-l2/src/main/java/com/tc/l2/ha/RandomWeightGenerator.java
- dso-l2/src/main/java/com/tc/l2/ha/WeightGeneratorFactory.java
- dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActivePassiveAckWaiter.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ReplicationSender.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ActivePassiveAckWaiterTest.java
- dso-l2/src/test/java/com/tc/objectserver/entity/ActiveToPassiveReplicationTest.java
Server message completion refactoring
Election deadlock fix
> Group error handling

- dso-l1/pom.xml
- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/main/java/com/tc/object/EntityClientEndpointImpl.java
- dso-l1/src/main/java/com/tc/object/ExceptionUtils.java
- dso-l1/src/main/java/com/tc/object/InFlightMessage.java
- dso-l1/src/main/java/com/tc/object/InFlightMonitor.java
- dso-l1/src/main/java/com/tc/object/InvocationHandler.java
- dso-l1/src/main/java/com/terracotta/diagnostic/DiagnosticClientEntityManager.java
- dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
- dso-l1/src/test/java/com/tc/object/InFlightMessageTest.java
- pom.xml
Please pay attention to the new tests in ClientEntityManagerTest.
> async invocation API implementation

- dso-l2/src/main/java/com/tc/l2/state/StateManager.java
- dso-l2/src/main/java/com/tc/l2/state/StateManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/test/java/com/tc/net/groups/TestStateManager.java
- dso-l2/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
Looks like known servers list is not used anywhere so removing the tracking code
> Cleanup unused known servers tracking code

- configuration-provider/src/main/java/com/terracotta/config/ConfigurationProvider.java
- dso-l2/src/main/java/com/tc/l2/ha/ClusterStateImpl.java
- dso-l2/src/main/java/com/tc/l2/ha/ReplicatedClusterStateManagerImpl.java
- tc-messaging/src/main/java/com/tc/l2/ha/ClusterState.java
- tc-messaging/src/main/java/com/tc/l2/msg/ClusterStateMessage.java
* Sync configuration only when COMPLETE_STATE received
* Simplify `ConfigurationProvider` API
> Sync configuration only when COMPLETE_STATE received

- terracotta-kit/src/assemble/init/sysv/terracotta.properties
- terracotta-kit/src/assemble/init/sysv/terracotta.sh
Same as #1073 but for master.
@myronkscott I picked a random location, feedback welcome
FYI @jhouserizer
> Init scripts (DAGGY master)

- terracotta-kit/src/assemble/init/sysv/terracotta.properties
- terracotta-kit/src/assemble/init/sysv/terracotta.sh
Same as #1072 but for release/5.6
> Adding sysv init scripts (DAGGY 5.6)

- voter/src/main/java/org/terracotta/voter/ActiveVoter.java
Currently host-ports passed on command-line used for re-registration, this might not work as topology might have changed and those host-ports are not part of the stripe.
> Use latest topology during re-registration

- voter/src/main/java/org/terracotta/voter/TCVoterMain.java
> Logging PID for voter process

- dso-l2/src/main/java/com/tc/l2/logging/TCLogbackLogging.java
- Always use console logger in TCLogbackLogging as logging is not yet initialized
- Fail if log dir could not be created or if the path is not a directory
- Fail for IOExceptions too
> Logging changes

- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- dso-l2/src/main/java/com/tc/config/ServerConfigurationManager.java
- dso-l2/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- dso-l2/src/main/java/com/tc/objectserver/impl/TopologyListener.java
- dso-l2/src/main/java/com/tc/objectserver/impl/TopologyManager.java
- galvan-support/src/test/java/org/terracotta/testing/rules/BasicExternalClusterFOPConsistencyVoterIT.java
- galvan-support/src/test/java/org/terracotta/testing/rules/DynamicPassiveRemovalIT.java
Update the signature of passive addition and removal to include group port.
> Fix the signature of passive mbean changes

- dso-l2/src/main/java/com/tc/objectserver/handler/ProcessTransactionHandler.java
- pom.xml
- terracotta-kit/pom.xml
> Update to latest parent

- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/main/java/com/tc/object/TransactionSource.java
- dso-l1/src/test/java/com/tc/object/TransactionSourceTest.java
- tc-messaging/src/main/java/com/tc/entity/ResendVoltronEntityMessage.java
- tc-messaging/src/test/java/com/tc/object/msg/ClientHandshakeMessageImplTest.java
Re-implement oldest transaction id tracking using a sliding window bitset retirement.
> Fix retirement of oldest transaction id

- dso-l1/src/main/java/com/tc/object/TransactionSource.java
- tc-messaging/src/main/java/com/tc/entity/ResendVoltronEntityMessage.java
- tc-messaging/src/main/java/com/tc/object/tx/TransactionID.java
cache needs to start at a valid transactionid
> Fix transaction source cache

- dso-l2/src/main/java/com/tc/objectserver/entity/ActivePassiveAckWaiter.java
- dso-l2/src/main/java/com/tc/objectserver/entity/ActiveToPassiveReplication.java
- pom.xml
> Release final

- dso-l2/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- dso-l2/src/main/java/com/tc/objectserver/persistence/NullPersistor.java
- dso-l2/src/main/java/com/tc/server/TCServerImpl.java
- galvan-support/src/main/java/org/terracotta/testing/rules/BasicInlineCluster.java
- galvan-support/src/test/java/org/terracotta/functional/InformationConnectionIT.java
- voter/src/main/java/org/terracotta/voter/ClientVoterManagerImpl.java
if a configuration is not complete.  persistence should not be a factor
> use null persistor if configuration is not complete

- dso-l2/src/main/java/com/tc/objectserver/handler/ClientChannelLifeCycleHandler.java
- dso-l2/src/main/java/com/tc/objectserver/handshakemanager/ClientHandshakeMonitoringInfo.java
- dso-l2/src/main/java/com/tc/server/TCServerImpl.java
- galvan-support/src/main/java/org/terracotta/testing/config/ArgOnlyStartupCommandBuilder.java
- galvan-support/src/main/java/org/terracotta/testing/config/DefaultStartupCommandBuilder.java
- galvan-support/src/main/java/org/terracotta/testing/config/TcConfigBuilder.java
- galvan-support/src/main/java/org/terracotta/testing/rules/BasicInlineCluster.java
- pom.xml
- server-bootstrap/src/main/java/com/tc/server/ServerFactory.java
- server-bootstrap/src/main/java/com/tc/server/TCServerMain.java
> Tag channel events

- common/src/main/java/com/tc/net/protocol/tcm/ClientMessageChannelImpl.java
- galvan-support/src/test/java/org/terracotta/functional/ShutdownFunctionIT.java
- voter/src/test/java/org/terracotta/voter/ActiveVoterTest.java
several random failures on tests repaired.
> Fix misc tests

- tc-server/src/main/java/com/tc/l2/logging/BufferingAppender.java
- tc-server/src/main/java/com/tc/l2/logging/TCLogbackLogging.java
- tc-server/src/main/java/com/tc/objectserver/handshakemanager/ServerClientHandshakeManager.java
log more about reconnecting clients to console
protect thread unsafe list of unconnected clients
> Fix reconnection behavior

- tc-server/src/main/java/com/tc/l2/state/ServerVoterManager.java
- tc-server/src/main/java/com/tc/l2/state/ServerVoterManagerImpl.java
- voter/src/main/java/org/terracotta/voter/ActiveVoter.java
- voter/src/main/java/org/terracotta/voter/ClientVoterManager.java
- voter/src/main/java/org/terracotta/voter/ClientVoterManagerImpl.java
- voter/src/test/java/org/terracotta/voter/ActiveVoterTest.java
Implements better voter tool feedback as described in TDB-3830
> TDB-3830 better feedback for voter tool

- terracotta-kit/src/assemble/server/bin/start-tc-server.bat
- terracotta-kit/src/assemble/voter/bin/start-tc-voter.bat
- terracotta-kit/src/test/java/com/tc/server/bin/StartTcServerScriptTest.java
- terracotta-kit/src/test/java/org/terracotta/voter/bin/StartTcVoterScriptTest.java
- terracotta-kit/src/test/resources/server/bin/start-tc-server.bat
- terracotta-kit/src/test/resources/voter/bin/start-tc-voter.bat
- test-common/src/main/java/com/tc/test/BaseScriptTest.java
Used the superset of disallowed characters from the SAG installer as the basis to determine check in the start scripts.
> test for invalid path char and update test.

- terracotta-kit/src/assemble/server/bin/start-tc-server.bat
- terracotta-kit/src/test/java/com/tc/server/bin/StartTcServerScriptTest.java
- terracotta-kit/src/test/resources/server/bin/start-tc-server.bat
- test-common/src/main/java/com/tc/test/BaseScriptTest.java
This reverts commit a0b161fdd06d12a78c9c496a2553fea533532b86, reversing
changes made to 48594972a3a4d78b33ebc563c49bdef0bbb48a01.
> Revert "Merge pull request #1260 from jko314/install-dir-check"

- build-parent/pom.xml
Signed-off-by: jhouserizer <jhouse@revolition.net>
> Bump logback-core and slf4j in build-parent

- tc-client/src/main/java/com/tc/object/BinaryInvocationCallback.java
- tc-client/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- tc-client/src/main/java/com/tc/object/EntityClientEndpointImpl.java
- tc-client/src/main/java/com/tc/object/InFlightMessage.java
- tc-client/src/main/java/com/tc/object/InvocationHandler.java
- tc-client/src/main/java/com/tc/object/SafeInvocationCallback.java
- tc-client/src/main/java/com/terracotta/diagnostic/DiagnosticClientEntityManager.java
- tc-client/src/test/java/com/tc/object/ClientEntityManagerTest.java
- tc-client/src/test/java/com/tc/object/SafeInvocationCallbackTest.java
This needs test coverage... but I think this kind of approach makes sense. If you're happy enough with the principle here, then I'll add some test coverage for the guard class and we can merge.
> Provide protection from untrusted callbacks when calling user code

- build-parent/pom.xml
slf4j-api 1.7.36
logback 1.2.11
> [5.6] Logging Upgrades

- dso-l1/src/main/java/com/tc/object/ClientEntityManagerImpl.java
- dso-l1/src/test/java/com/tc/object/ClientEntityManagerTest.java
(cherry picked from commit 19a16b30ba415e9d073714e951df1b6ac9f74ae4)
> Fixes #1125 : Only advance low-watermark on send failure if the message was not queued.

- common/src/main/java/com/tc/net/protocol/tcm/CommunicationsManagerImpl.java
- common/src/main/java/com/tc/net/protocol/transport/ConnectionHealthCheckerImpl.java
- galvan-support/src/test/java/org/terracotta/testing/rules/ClientLeakIT.java
- tc-client/src/main/java/com/terracotta/diagnostic/DiagnosticClientBuilder.java
Add health-check to diagnostic connections
Move to a single health-check executor per classloader
> Client health check changes

- tc-server/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- tc-server/src/test/java/com/tc/net/groups/TCGroupManagerImplTest.java
don't wait for meager that will never come from a missing server peer.
> Half duplex

- common/src/main/java/com/tc/net/basic/BasicConnection.java
- common/src/main/java/com/tc/net/core/TCConnectionImpl.java
- common/src/main/java/com/tc/net/protocol/tcm/TCMessageParser.java
- common/src/main/java/com/tc/net/protocol/transport/ClientMessageTransport.java
- common/src/main/java/com/tc/net/protocol/transport/MessageTransportBase.java
- common/src/main/java/com/tc/net/protocol/transport/ServerMessageTransport.java
- common/src/test/java/com/tc/net/protocol/tcm/TestTCMessage.java
- common/src/test/java/com/tc/net/protocol/transport/TCConnectionTransportTest.java
- tc-messaging/src/main/java/com/tc/bytes/TCByteBufferImpl.java
- tc-messaging/src/main/java/com/tc/bytes/TCDirectByteBufferCache.java
- tc-messaging/src/main/java/com/tc/entity/NetworkVoltronEntityMessageImpl.java
- tc-messaging/src/main/java/com/tc/net/groups/TCGroupMessageWrapper.java
- tc-messaging/src/main/java/com/tc/net/protocol/tcm/TCAction.java
- tc-messaging/src/main/java/com/tc/net/protocol/tcm/TCActionImpl.java
- tc-messaging/src/main/java/com/tc/net/protocol/transport/WireProtocolAdaptorImpl.java
- tc-messaging/src/main/java/com/tc/net/protocol/transport/WireProtocolGroupMessageImpl.java
- tc-messaging/src/main/java/com/tc/object/msg/ClientHandshakeMessageImpl.java
- tc-messaging/src/test/java/com/tc/entity/NetworkVoltronEntityMessageImplTest.java
- tc-messaging/src/test/java/com/tc/object/msg/ClientHandshakeMessageTest.java
- tc-server/src/main/java/com/tc/net/groups/TCGroupMemberImpl.java
- tc-server/src/main/java/com/tc/objectserver/entity/CloseableActiveInvokeChannel.java
I did not add a test as it is a usage problem.  The first commit fixes the problem.  The other commits are code cleanup of things that bothered me while inspecting this issue.
> Code cleanup while investigating data corruption

- common/pom.xml
- common/src/main/java/com/tc/net/protocol/transport/ClientConnectionEstablisher.java
- common/src/test/java/com/tc/net/protocol/transport/ClientConnectionEstablisherTest.java
Make attempts to reconnect cease if the thread  is interrupted.
Also did some cleanup and added a test.
> update reconnect thread 

- common/src/main/java/com/tc/net/core/TCWorkerCommManager.java
- management/src/main/java/com/tc/management/beans/L2MBeanNames.java
- tc-server/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- tc-server/src/main/java/com/tc/objectserver/core/api/ServerConfigurationContext.java
- tc-server/src/main/java/com/tc/objectserver/entity/ReplicationSender.java
- tc-server/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- tc-server/src/main/java/com/tc/objectserver/impl/TopologyManager.java
- tc-server/src/test/java/com/tc/net/groups/MockStageManagerFactory.java
- tc-server/src/test/java/com/tc/objectserver/entity/ReplicationSenderTest.java
move replication flush to its own stage to control batching and packet size.
> Fix replication flush sequence

- galvan-support/pom.xml
- galvan-support/src/main/java/org/terracotta/testing/rules/BasicInlineCluster.java
- galvan-support/src/test/java/org/terracotta/testing/rules/BasicInlineClusterIT.java
- galvan-support/src/test/resources/tc-config.xml
- tc-server/src/main/java/com/tc/server/Bootstrap.java
- tc-server/src/main/java/com/tc/server/TCServerImpl.java
Issue was found with management holding references to inline servers during tests.  Fix implementation and add test.
> make sure inline server is garbage collectible after shutdown

- common/src/main/java/com/tc/async/api/StageManager.java
- common/src/main/java/com/tc/async/impl/StageManagerImpl.java
- common/src/main/java/com/tc/net/core/TCConnectionImpl.java
- common/src/main/java/com/tc/net/protocol/tcm/MessageMonitorImpl.java
- common/src/main/java/com/tc/properties/TCPropertiesConsts.java
- common/src/main/resources/com/tc/properties/tc.properties
- common/src/test/java/com/tc/async/impl/StageManagerImplTest.java
- common/src/test/java/com/tc/async/impl/TCNotRunningTest.java
- common/src/test/java/com/tc/net/protocol/tcm/MessageMonitorImplTest.java
- galvan-support/src/test/resources/tc-config.xml
- tc-client/src/main/java/com/tc/object/DistributedObjectClient.java
- tc-server/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- tc-server/src/main/java/com/tc/objectserver/entity/RequestProcessor.java
- tc-server/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- tc-server/src/main/java/com/tc/objectserver/impl/ServerBuilder.java
- tc-server/src/main/java/com/tc/objectserver/impl/StandardServerBuilder.java
- tc-server/src/test/java/com/tc/l2/state/StateManagerImplTest.java
- tc-server/src/test/java/com/tc/net/groups/MockStageManagerFactory.java
- tc-server/src/test/java/com/tc/net/groups/TestStateManagerFactory.java
- tc-server/src/test/java/com/tc/objectserver/entity/RequestProcessorTest.java
- tc-server/src/test/java/com/tc/objectserver/handler/ProcessTransactionHandlerTest.java
Cleanup some config code and add some additional logging.
> Stage config cleanup

- tc-messaging/src/main/java/com/tc/util/Conversion.java
Quiet scanners.  This class is currently unused
> [5.10] Update conversion class to be more thread safe

- common/src/main/java/com/tc/lang/ThrowableHandlerImpl.java
- common/src/test/java/com/tc/lang/ThrowableHandlerTest.java
> [MAIN]  Remove JMX thread detection and handling

- build.gradle
- client-api/build.gradle
- client-runtime/build.gradle
- common-api/build.gradle
- galvan-support/build.gradle
- galvan/build.gradle
- gradle.properties
- passthrough-server/build.gradle
- server-api/build.gradle
- server-runtime/build.gradle
- test-interfaces/build.gradle
also removed useless repositories which no longer exist for maven.
> use buildVersion instead of overrideVersion for publishing

- build.gradle
- common/src/main/java/com/tc/net/core/TCListener.java
- common/src/main/java/com/tc/net/core/TCListenerImpl.java
- common/src/main/java/com/tc/net/protocol/tcm/CommunicationsManagerImpl.java
- common/src/main/java/com/tc/net/protocol/tcm/NetworkListener.java
- common/src/main/java/com/tc/net/protocol/tcm/NetworkListenerImpl.java
- common/src/test/java/com/tc/net/core/NoReconnectThreadTest.java
- common/src/test/java/com/tc/net/core/TCWorkerCommManagerTest.java
- common/src/test/java/com/tc/net/protocol/tcm/LazyHandshakeTest.java
- common/src/test/java/com/tc/net/protocol/tcm/MessageChannelTest.java
- common/src/test/java/com/tc/net/protocol/tcm/NetworkListenerTest.java
- tc-server/src/main/java/com/tc/net/groups/NullTCGroupMemberDiscovery.java
- tc-server/src/main/java/com/tc/net/groups/TCGroupManagerImpl.java
- tc-server/src/main/java/com/tc/net/groups/TCGroupMemberDiscovery.java
- tc-server/src/main/java/com/tc/net/groups/TCGroupMemberDiscoveryStatic.java
- tc-server/src/main/java/com/tc/objectserver/impl/DistributedObjectServer.java
- tc-server/src/test/java/com/tc/net/groups/TCGroupManagerNodeJoinedTest.java
Also update shutdown to not use unpredictable timeouts.
> Update artifactory publish dependency

- gradle.properties
logback and slf4j are not matched in api
> bump api version to move logback to latest version

- gradle.properties
- tc-server/src/main/java/com/tc/l2/logging/BootstrapConfigurator.java
- tc-server/src/main/java/com/tc/l2/logging/TCLogbackLogging.java
This is an alternative to the other PR https://github.com/Terracotta-OSS/terracotta-core/pull/1381
This one simplifies the BootstrapConfigurator to set the default logging level to INFO
> Force Logback to INFO level
